#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Facility/ViewInfo.cshtml")]
    public partial class _Views_Facility_ViewInfo_cshtml : WebApp.Core.BaseWebViewPage<Facility.ViewInfo>
    {
        public _Views_Facility_ViewInfo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"col-8_xs-12\"");

WriteLiteral(">");

            
            #line 4 "..\..\Views\Facility\ViewInfo.cshtml"
                       Write(Html.LockedText(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 5 "..\..\Views\Facility\ViewInfo.cshtml"
                       Write(Html.LockedText(m => m.FacilityType));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n   <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 7 "..\..\Views\Facility\ViewInfo.cshtml"
                       Write(Html.LockedText(m => m.Phone));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 8 "..\..\Views\Facility\ViewInfo.cshtml"
                       Write(Html.LockedText(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Facility\ViewInfo.cshtml"
                       Write(Html.LockedText(m => m.Website));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 11 "..\..\Views\Facility\ViewInfo.cshtml"
                  Write(Html.LockedText(m => m.Address));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Facility\ViewInfo.cshtml"
                  Write(Html.LockedText(m => m.Note, true));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
