#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CompanyUser/EditTemplate.cshtml")]
    public partial class _Views_CompanyUser_EditTemplate_cshtml : WebApp.Core.BaseWebViewPage<CompanyUser>
    {
        public _Views_CompanyUser_EditTemplate_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\CompanyUser\EditTemplate.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n   window.HasGroupId = function () { return ");

            
            #line 4 "..\..\Views\CompanyUser\EditTemplate.cshtml"
                                        Write(Model.HasGroupId() ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral("; }\r\n   window.HasDataId = function () { return ");

            
            #line 5 "..\..\Views\CompanyUser\EditTemplate.cshtml"
                                       Write(CompanyUser.UserDatas != null ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(" && !!Permission.GetValue() ; }\r\n</script>\r\n<div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"col-8_xs-12 grid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 10 "..\..\Views\CompanyUser\EditTemplate.cshtml"
    Write(Html.EditorFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 13 "..\..\Views\CompanyUser\EditTemplate.cshtml"
    Write(Html.EditorFor(m => m.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 16 "..\..\Views\CompanyUser\EditTemplate.cshtml"
    Write(Html.EditorFor(m => m.Address));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 19 "..\..\Views\CompanyUser\EditTemplate.cshtml"
    Write(Html.EditorFor(m => m.Phone));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 22 "..\..\Views\CompanyUser\EditTemplate.cshtml"
    Write(Html.EditorFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n");

            
            #line 24 "..\..\Views\CompanyUser\EditTemplate.cshtml"
      
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\CompanyUser\EditTemplate.cshtml"
       if (Model.IsNew())
      {

            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 27 "..\..\Views\CompanyUser\EditTemplate.cshtml"
       Write(Html.EditorFor(m => m.Password));

            
            #line default
            #line hidden
WriteLiteral("\r\n         </div>\r\n");

WriteLiteral("         <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 30 "..\..\Views\CompanyUser\EditTemplate.cshtml"
       Write(Html.EditorFor(m => m.Verify));

            
            #line default
            #line hidden
WriteLiteral("\r\n         </div>\r\n");

            
            #line 32 "..\..\Views\CompanyUser\EditTemplate.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("   </div>\r\n   <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(" style=\"min-height: 200px;\"");

WriteLiteral(">\r\n");

WriteLiteral("      ");

            
            #line 35 "..\..\Views\CompanyUser\EditTemplate.cshtml"
 Write(Html.DevExpress().BinaryImageFor(m => m.Image, st =>
      {
         st.Width = Unit.Percentage(100);
         st.Height = Unit.Percentage(100);
         st.CallbackRouteValues = new { Action = "UpdateUserImage" };
         st.Properties.ImageWidth = 300;
         st.Properties.ImageHeight = 300;
         st.Properties.ImageSizeMode = ImageSizeMode.FitProportional;
         st.Properties.EditingSettings.Enabled = true;
         st.Properties.EditingSettings.AllowDropOnPreview = true;
         st.Properties.EditingSettings.UploadSettings.UploadValidationSettings.MaxFileSize = 1000000;
      }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"col-12 grid\"");

WriteLiteral(">\r\n");

            
            #line 49 "..\..\Views\CompanyUser\EditTemplate.cshtml"
      
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\CompanyUser\EditTemplate.cshtml"
       if (CompanyUser.UserGroupsView != null)
      {

            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Views\CompanyUser\EditTemplate.cshtml"
       Write(CompanyUser.UserGroupsView(Html));

            
            #line default
            #line hidden
WriteLiteral("\r\n         </div>\r\n");

            
            #line 54 "..\..\Views\CompanyUser\EditTemplate.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 56 "..\..\Views\CompanyUser\EditTemplate.cshtml"
    Write(Html.DevExpress().ComboBoxFor(m => m.Permission, st =>
    {
       st.Width = Unit.Percentage(100);
       st.Properties.Caption = T("Quyền sử dụng");
       st.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
       st.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
       st.Properties.IncrementalFilteringDelay = 1000;
       st.Properties.DropDownStyle = DropDownStyle.DropDownList;
       st.Properties.ValueField = "Key";
       st.Properties.ValueType = typeof(int);
       st.Properties.TextField = "Value";
       st.ShowModelErrors = true;
       st.Properties.ValidationSettings.Display = Display.Dynamic;
       st.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
       st.Properties.CaptionSettings.RequiredMarkDisplayMode = EditorRequiredMarkMode.Required;
       st.Properties.SettingsAdaptivity.Mode = DropDownEditAdaptivityMode.OnWindowInnerWidth;
       st.Properties.SettingsAdaptivity.SwitchToModalAtWindowInnerWidth = WidthAdaptivity;
       st.Properties.ClientSideEvents.ValueChanged = "function() {UpdateUIPermissionData();}";
    }).BindList(Model.GetPermissions()).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n");

            
            #line 76 "..\..\Views\CompanyUser\EditTemplate.cshtml"
      
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\CompanyUser\EditTemplate.cshtml"
       if (CompanyUser.UserDatasView != null)
      {

            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"col-6_xs-12 cmbPermissionData\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 79 "..\..\Views\CompanyUser\EditTemplate.cshtml"
       Write(CompanyUser.UserDatasView(Html));

            
            #line default
            #line hidden
WriteLiteral("\r\n         </div>\r\n");

            
            #line 81 "..\..\Views\CompanyUser\EditTemplate.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(" style=\"align-self: end;\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 83 "..\..\Views\CompanyUser\EditTemplate.cshtml"
    Write(Html.EditorFor(m => m.Active));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">\r\n");

WriteLiteral("      ");

            
            #line 88 "..\..\Views\CompanyUser\EditTemplate.cshtml"
 Write(Html.EditorFor(m => m.Note));

            
            #line default
            #line hidden
WriteLiteral("\r\n   </div>\r\n</div>\r\n<script");

WriteLiteral(" id=\"dxss_updatepermissiondata\"");

WriteLiteral(">\r\n   function UpdateUIPermissionData() {\r\n      $(\'.cmbPermissionData\').toggle(!" +
"!Permission.GetValue());\r\n   }\r\n   setTimeout(function () {\r\n      UpdateUIPermi" +
"ssionData();\r\n   });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
