#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SharedData/Index.cshtml")]
    public partial class _Views_SharedData_Index_cshtml : WebApp.Core.BaseWebViewPage<dynamic>
    {
        public _Views_SharedData_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"page-container\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"page-header grid-middle\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"mr img contact\"");

WriteLiteral("></div>\r\n      <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 5 "..\..\Views\SharedData\Index.cshtml"
    Write(H("Duyệt hồ sơ chuyển vùng"));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"page-content\"");

WriteLiteral(">\r\n      <form>\r\n");

WriteLiteral("         ");

            
            #line 10 "..\..\Views\SharedData\Index.cshtml"
    Write(Html.Partial("IndexPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n      </form>\r\n   </div>\r\n</div>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n   WebApp.function = {\r\n      title: \'");

            
            #line 17 "..\..\Views\SharedData\Index.cshtml"
         Write(H("Duyệt hồ sơ chuyển vùng"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n      permission: {\r\n         del: ");

            
            #line 19 "..\..\Views\SharedData\Index.cshtml"
         Write(CheckPermission("Xóa").ToString().ToLower());

            
            #line default
            #line hidden
WriteLiteral(@",
      },
      del: function () {
         if (WebApp.loading() || !WebApp.function.permission.del) return;
         var idx = grdSheet.GetFocusedRowIndex();
         var id = grdSheet.GetRowKey(idx);
         if (!id) return;
         WebApp.showConfirm(WebApp.message.delete, WebApp.message.deleteConfirm).done(function (r) {
            WebApp.ajax('");

            
            #line 27 "..\..\Views\SharedData\Index.cshtml"
                    Write(Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteral(@"', {id: id}).done(function() {
               grdSheet.PerformCallback();
            });
         });
      },
      export: function () {
         grdSheet.ExportTo(ASPxClientGridViewExportFormat.Xlsx);
      },
      filter: function () {
         grdSheet._showFilter = !(grdSheet._showFilter || false);
         grdSheet.PerformCallback();
      },
      hotkey: {
         f4: function() { WebApp.function.del(); },
         f5: function () { grdSheet.PerformCallback(); },
         esc: function () { WebApp.function.close(); },
      },
      resize: function () {
         $('.page-content').height($('.page-container').height() - $('.page-header').height());
         grdSheet.SetHeight($('.page-content').innerHeight());
      },
      close: WebApp.closeFunction.bind(WebApp),
      update: function() {
         var idx = grdSheet.GetFocusedRowIndex();
         var tool = grdSheet.GetToolbar(0);
         tool.GetItemByName(""del"").SetEnabled(idx !== -1);
      },
      updateAccept: function (id, accept) {
         WebApp.ajax('");

            
            #line 55 "..\..\Views\SharedData\Index.cshtml"
                 Write(Url.Action("UpdateAccept"));

            
            #line default
            #line hidden
WriteLiteral("\', { id: id, accept: accept });\r\n      }\r\n   };\r\n</script>");

        }
    }
}
#pragma warning restore 1591
