#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ProgramResult/IndexPartial.cshtml")]
    public partial class _Views_ProgramResult_IndexPartial_cshtml : WebApp.Core.BaseWebViewPage<ProgramResult>
    {
        public _Views_ProgramResult_IndexPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\ProgramResult\IndexPartial.cshtml"
Write(Html.DevExpress().CallbackPanel(st =>
{
   st.Name = "panelProgramResult";
   st.Height = Unit.Percentage(100);
   st.Width = Unit.Percentage(100);
   st.CallbackRouteValues = new { Action = "IndexPartial" };
   st.SetContent(() =>
   {
      if (Model == null) return;
      Html.DevExpress().PageControl(pc =>
      {
         pc.Name = "pcProgramResult";
         pc.Height = Unit.Percentage(100);
         pc.Width = Unit.Percentage(100);
         pc.TabPages.Add(t =>
         {
            t.Text = T("Kết quả đào tạo");
            t.SetContent(() =>
            {
               ViewContext.Writer.Write("<form class='frmProgramResult' style='display:block; height: 100%;'>");
               Html.RenderPartial("Doctors");
               ViewContext.Writer.Write("</form>");
            });
         });
         pc.TabPages.Add(t =>
         {
            t.Text = T("Nội dung đào tạo");
            t.SetContent(() =>
            {
               ViewContext.Writer.Write("<form class='frmProgramResultAttachment' style='display:block; height: 100%;'>");
               ViewContext.Writer.Write(Html.EditorFor(m => m.Attachments));
               ViewContext.Writer.Write("</form>");
            });
         });
      }).Render();

   });
   st.ClientSideEvents.BeginCallback = "function(s,e) {e.customArgs.program = cmbProgram.GetValue();}";
   st.ClientSideEvents.EndCallback = "function() {WebApp.function.afterReload();}";
}).GetHtml());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
