#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Medical/BeginProcess.cshtml")]
    public partial class _Views_Medical_BeginProcess_cshtml : WebApp.Core.BaseWebViewPage<BeginProcess>
    {
        public _Views_Medical_BeginProcess_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"dxss_beginprocess\"");

WriteLiteral(">\r\n   function onBeginProcessSave() {\r\n      if (!WebApp.validForm(\'#frmBeginProc" +
"ess\')) return;\r\n      if (NoProcess.GetValue() === false && !AttachmentListBegin" +
"Process.GetVisibleRowsOnPage()) {\r\n         WebApp.showInfo(\'");

            
            #line 7 "..\..\Views\Medical\BeginProcess.cshtml"
                     Write(H("Lỗi"));

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 7 "..\..\Views\Medical\BeginProcess.cshtml"
                                  Write(H("Vui lòng cập nhật tài liệu, hình ảnh, video kèm theo!"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n         return;\r\n      }\r\n      BeginProcessSave.SetEnabled(false);\r\n      " +
"WebApp.ajax(\'");

            
            #line 11 "..\..\Views\Medical\BeginProcess.cshtml"
              Write(Url.Action("BeginProcess", "Medical"));

            
            #line default
            #line hidden
WriteLiteral(@"', getBeginData()).done(function (r) {
         processModel.reload();
      }).fail(function () { BeginProcessSave.SetEnabled(true); });
   }

   function getBeginData() {
      var d = EvaluationDate.GetDate();
      return {
         Id: processModel.id,
         EvaluationDate: d && d.toISOString() || null,
         EvaluationTool: EvaluationTool.GetValue(),
         EvaluationPoint: EvaluationPoint.GetValue(),
         Evaluation: Evaluation.GetValue(),
         Diagnostics: Diagnostics.GetValue(),
         DiagnosticsValue: $('#DiagnosticsValue').val(),
         Treatments: Treatments.GetValue(),
         TreatmentsValue: $('#TreatmentsValue').val(),
         Services: Services.GetValue(),
         ServicesValue: $('#ServicesValue').val(),
         Attachments: { Items: AttachmentListBeginProcess.GetChanged(), },
         Doctors: { Items: DoctorsBeginProcess.GetSelectedValues().map(function (id) { return { Id: id }; }), Facility: ");

            
            #line 31 "..\..\Views\Medical\BeginProcess.cshtml"
                                                                                                                    Write(Model.Doctors.Facility);

            
            #line default
            #line hidden
WriteLiteral(" },\r\n         NoProcess: NoProcess.GetValue(),\r\n         ReasonCancel: ReasonCanc" +
"el.GetValue(),\r\n      };\r\n   }\r\n\r\n   function updateUI() {\r\n      const b = NoPr" +
"ocess.GetValue();\r\n      $(\'#frmBeginProcess .service\').toggle(b===false);\r\n    " +
"  $(\'#frmBeginProcess .treatment\').toggle(b===false);\r\n      $(\'#frmBeginProcess" +
" .reasoncancel\').toggle(b===true);\r\n   }\r\n\r\n   setTimeout(function () {\r\n      W" +
"ebApp.validateForm(\'#frmBeginProcess\');\r\n      var oldData = JSON.stringify(getB" +
"eginData());\r\n\r\n      [EvaluationDate, EvaluationTool, EvaluationPoint, Evaluati" +
"on, Diagnostics, Treatments, Services, NoProcess, ReasonCancel].forEach(function" +
" (it) {\r\n         it.ValueChanged.AddHandler(function () {\r\n            var d = " +
"JSON.stringify(getBeginData());\r\n            BeginProcessSave.SetVisible(d != ol" +
"dData);\r\n         });\r\n      });\r\n      AttachmentListBeginProcess.onDataChanged" +
" = function (data) {\r\n         var d = JSON.stringify(getBeginData());\r\n        " +
" BeginProcessSave.SetVisible(d != oldData);\r\n      };\r\n      DoctorsBeginProcess" +
".SelectedIndexChanged.AddHandler(function () {\r\n         var d = JSON.stringify(" +
"getBeginData());\r\n         BeginProcessSave.SetVisible(d != oldData);\r\n      });" +
"\r\n\r\n      updateUI();\r\n      NoProcess.ValueChanged.AddHandler(function () {\r\n  " +
"       updateUI();\r\n      });\r\n   });\r\n\r\n   window.CheckReasonCancel = function " +
"() {\r\n      return NoProcess.GetValue() === true;\r\n   }\r\n\r\n   window.CheckServic" +
"e = function () {\r\n      return NoProcess.GetValue() === false;\r\n   }\r\n</script>" +
"\r\n\r\n<form");

WriteLiteral(" id=\"frmBeginProcess\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-auto_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 80 "..\..\Views\Medical\BeginProcess.cshtml"
                                  Write(Html.EditorFor(m => m.EvaluationDate));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-auto_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 81 "..\..\Views\Medical\BeginProcess.cshtml"
                                  Write(Html.EditorFor(m => m.EvaluationTool));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-auto_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 82 "..\..\Views\Medical\BeginProcess.cshtml"
                                  Write(Html.EditorFor(m => m.EvaluationPoint));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 83 "..\..\Views\Medical\BeginProcess.cshtml"
                             Write(Html.EditorFor(m => m.Evaluation));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 84 "..\..\Views\Medical\BeginProcess.cshtml"
                     Write(Html.EditorFor(m => m.Diagnostics));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-12 grid-middle-noBottom\"");

WriteLiteral(">\r\n         <div");

WriteLiteral(" class=\"col-auto_xs-12\"");

WriteLiteral(">");

            
            #line 86 "..\..\Views\Medical\BeginProcess.cshtml"
                                Write(H("Đề xuất can thiệp PHCN"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n         <div");

WriteLiteral(" class=\"col-auto_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 88 "..\..\Views\Medical\BeginProcess.cshtml"
       Write(Html.DevExpress().RadioButtonListFor(m => m.NoProcess, st =>
       {
          st.Properties.RepeatColumns = 2;
          st.Properties.Items.Add(T("Có"), false);
          st.Properties.Items.Add(T("Không"), true);
          st.ControlStyle.Border.BorderWidth = 0;
          st.Properties.EnableClientSideAPI = true;
          st.Properties.ValueType = typeof(bool?);
          st.ShowModelErrors = true;
          st.Properties.ValidationSettings.Display = Display.Dynamic;
          st.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
       }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n         </div>\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-12 treatment\"");

WriteLiteral(">");

            
            #line 102 "..\..\Views\Medical\BeginProcess.cshtml"
                               Write(Html.EditorFor(m => m.Treatments));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-12 service\"");

WriteLiteral(">");

            
            #line 103 "..\..\Views\Medical\BeginProcess.cshtml"
                             Write(Html.EditorFor(m => m.Services));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-12 reasoncancel\"");

WriteLiteral(">");

            
            #line 104 "..\..\Views\Medical\BeginProcess.cshtml"
                                  Write(Html.EditorFor(m => m.ReasonCancel));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 105 "..\..\Views\Medical\BeginProcess.cshtml"
                     Write(Html.EditorFor(m => m.Doctors));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 106 "..\..\Views\Medical\BeginProcess.cshtml"
                     Write(Html.EditorFor(m => m.Attachments));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   </div>\r\n   <div>\r\n");

WriteLiteral("      ");

            
            #line 109 "..\..\Views\Medical\BeginProcess.cshtml"
 Write(Html.DevExpress().Button(btn =>
{
 btn.Name = "BeginProcessSave";
 btn.Text = T("Lưu thay đổi");
 btn.Images.Image.IconID = IconID.SaveSave16x16;
 btn.Styles.Style.Paddings.Padding = 0;
 btn.RenderMode = ButtonRenderMode.Outline;
 btn.ClientVisible = false;
 btn.ClientSideEvents.Click = "onBeginProcessSave";
}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n   </div>\r\n\r\n</form>");

        }
    }
}
#pragma warning restore 1591
