#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Medical/FacilityProcess.cshtml")]
    public partial class _Views_Medical_FacilityProcess_cshtml : WebApp.Core.BaseWebViewPage<FacilityProcess>
    {
        public _Views_Medical_FacilityProcess_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Medical\FacilityProcess.cshtml"
  
   var suffix = "Ind" + Model.Id;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" id=\"dxss_FacilityProcess\"");

WriteLiteral(">\r\n   function onFacilityProcessSave");

            
            #line 6 "..\..\Views\Medical\FacilityProcess.cshtml"
                             Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("(btn) {\r\n      if (!WebApp.validForm(\'#frmFacilityProcess");

            
            #line 7 "..\..\Views\Medical\FacilityProcess.cshtml"
                                            Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("\')) return;\r\n      if (!AttachmentListFacilityProcess");

            
            #line 8 "..\..\Views\Medical\FacilityProcess.cshtml"
                                    Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(".GetVisibleRowsOnPage()) {\r\n         WebApp.showInfo(\'");

            
            #line 9 "..\..\Views\Medical\FacilityProcess.cshtml"
                     Write(H("Lỗi"));

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 9 "..\..\Views\Medical\FacilityProcess.cshtml"
                                  Write(H("Vui lòng cập nhật tài liệu, hình ảnh, video kèm theo!"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n         return;\r\n      }\r\n      btn.SetEnabled(false);\r\n      WebApp.ajax(\'" +
"");

            
            #line 13 "..\..\Views\Medical\FacilityProcess.cshtml"
              Write(Url.Action("FacilityProcess", "Medical"));

            
            #line default
            #line hidden
WriteLiteral("\', getFacilityData");

            
            #line 13 "..\..\Views\Medical\FacilityProcess.cshtml"
                                                                          Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("()).done(function (r) {\r\n         processModel.reload();\r\n      }).fail(function " +
"() { btn.SetEnabled(true); });\r\n   }\r\n\r\n   function onFacilityProcessDelete");

            
            #line 18 "..\..\Views\Medical\FacilityProcess.cshtml"
                               Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("() {\r\n      WebApp.showConfirm(\'");

            
            #line 19 "..\..\Views\Medical\FacilityProcess.cshtml"
                     Write(H("Xóa"));

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 19 "..\..\Views\Medical\FacilityProcess.cshtml"
                                  Write(H("Bạn có muốn xóa dữ liệu và tài liệu của lần can thiệp này không?"));

            
            #line default
            #line hidden
WriteLiteral("\').done(function () {\r\n         WebApp.ajax(\'");

            
            #line 20 "..\..\Views\Medical\FacilityProcess.cshtml"
                 Write(Url.Action("DeleteFacilityProcess", "Medical"));

            
            #line default
            #line hidden
WriteLiteral("\', { id: ");

            
            #line 20 "..\..\Views\Medical\FacilityProcess.cshtml"
                                                                         Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("}).done(function () {\r\n            processModel.reload();\r\n         });\r\n      })" +
";\r\n   }\r\n\r\n   function getFacilityData");

            
            #line 26 "..\..\Views\Medical\FacilityProcess.cshtml"
                       Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("() {\r\n      var dIn = DateIn");

            
            #line 27 "..\..\Views\Medical\FacilityProcess.cshtml"
                  Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(".GetDate();\r\n      var dOut = DateOut");

            
            #line 28 "..\..\Views\Medical\FacilityProcess.cshtml"
                    Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(".GetDate();\r\n      return {\r\n         Id: ");

            
            #line 30 "..\..\Views\Medical\FacilityProcess.cshtml"
        Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(",\r\n         DateIn: dIn && dIn.toISOString() || null,\r\n         DateOut: dOut && " +
"dOut.toISOString() || null,\r\n         Service: ProcessService");

            
            #line 33 "..\..\Views\Medical\FacilityProcess.cshtml"
                            Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(".GetValue(),\r\n         Status: ProcessStatus");

            
            #line 34 "..\..\Views\Medical\FacilityProcess.cshtml"
                          Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(".GetValue(),\r\n         Reason: ProcessReason");

            
            #line 35 "..\..\Views\Medical\FacilityProcess.cshtml"
                          Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(".GetValue(),\r\n         Attachments: { Items: AttachmentListFacilityProcess");

            
            #line 36 "..\..\Views\Medical\FacilityProcess.cshtml"
                                                        Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(".GetChanged(), },\r\n         Doctors: { Items: DoctorsFacilityProcess");

            
            #line 37 "..\..\Views\Medical\FacilityProcess.cshtml"
                                             Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(".GetSelectedValues().map(function (id) { return { Id: id }; }), Facility: ");

            
            #line 37 "..\..\Views\Medical\FacilityProcess.cshtml"
                                                                                                                                  Write(Model.Doctors.Facility);

            
            #line default
            #line hidden
WriteLiteral(" },\r\n      };\r\n   }\r\n\r\n   $(function () {\r\n      WebApp.validateForm(\'#frmFacilit" +
"yProcess");

            
            #line 42 "..\..\Views\Medical\FacilityProcess.cshtml"
                                          Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n      var oldData = JSON.stringify(getFacilityData");

            
            #line 43 "..\..\Views\Medical\FacilityProcess.cshtml"
                                              Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("());\r\n\r\n      [DateIn");

            
            #line 45 "..\..\Views\Medical\FacilityProcess.cshtml"
         Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(", DateOut");

            
            #line 45 "..\..\Views\Medical\FacilityProcess.cshtml"
                           Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(", ProcessService");

            
            #line 45 "..\..\Views\Medical\FacilityProcess.cshtml"
                                                    Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(", ProcessStatus");

            
            #line 45 "..\..\Views\Medical\FacilityProcess.cshtml"
                                                                            Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(", ProcessReason");

            
            #line 45 "..\..\Views\Medical\FacilityProcess.cshtml"
                                                                                                    Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("].forEach(function (it) {\r\n         it.ValueChanged.AddHandler(function () {\r\n   " +
"         const d = JSON.stringify(getFacilityData");

            
            #line 47 "..\..\Views\Medical\FacilityProcess.cshtml"
                                                Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("());\r\n            FacilityProcessSave");

            
            #line 48 "..\..\Views\Medical\FacilityProcess.cshtml"
                           Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(".SetVisible(d != oldData);\r\n         });\r\n      });\r\n      AttachmentListFacility" +
"Process");

            
            #line 51 "..\..\Views\Medical\FacilityProcess.cshtml"
                               Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(".onDataChanged = function (data) {\r\n         const d = JSON.stringify(getFacility" +
"Data");

            
            #line 52 "..\..\Views\Medical\FacilityProcess.cshtml"
                                             Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("());\r\n         FacilityProcessSave");

            
            #line 53 "..\..\Views\Medical\FacilityProcess.cshtml"
                        Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(".SetVisible(d != oldData);\r\n      }\r\n      DoctorsFacilityProcess");

            
            #line 55 "..\..\Views\Medical\FacilityProcess.cshtml"
                        Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(".SelectedIndexChanged.AddHandler(function () {\r\n         const d = JSON.stringify" +
"(getFacilityData");

            
            #line 56 "..\..\Views\Medical\FacilityProcess.cshtml"
                                             Write(suffix);

            
            #line default
            #line hidden
WriteLiteral("());\r\n         FacilityProcessSave");

            
            #line 57 "..\..\Views\Medical\FacilityProcess.cshtml"
                        Write(suffix);

            
            #line default
            #line hidden
WriteLiteral(".SetVisible(d != oldData);\r\n      });\r\n   });\r\n</script>\r\n<form");

WriteAttribute("id", Tuple.Create(" id=\"", 2713), Tuple.Create("\"", 2745)
, Tuple.Create(Tuple.Create("", 2718), Tuple.Create("frmFacilityProcess", 2718), true)
            
            #line 61 "..\..\Views\Medical\FacilityProcess.cshtml"
, Tuple.Create(Tuple.Create("", 2736), Tuple.Create<System.Object, System.Int32>(suffix
            
            #line default
            #line hidden
, 2736), false)
);

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-auto_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 64 "..\..\Views\Medical\FacilityProcess.cshtml"
    Write(Html.DevExpress().DateEditFor(m => m.DateIn, st =>
    {
       st.Name = "DateIn" + suffix;
       st.Width = Unit.Percentage(100);
       st.Properties.MinDate = Model.MinDate;
       st.Properties.MaxDate = DateTime.Today;
       st.Properties.AllowNull = false;
       st.ShowModelErrors = true;
       st.Properties.ValidationSettings.Display = Display.Dynamic;
       st.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
       st.Properties.CaptionSettings.RequiredMarkDisplayMode = EditorRequiredMarkMode.Required;
       st.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
       st.Properties.Caption = T("Ngày vào viện");
    }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-auto_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 80 "..\..\Views\Medical\FacilityProcess.cshtml"
    Write(Html.DevExpress().DateEditFor(m => m.DateOut, st =>
    {
       st.Name = "DateOut" + suffix;
       st.Width = Unit.Percentage(100);
       st.Properties.MinDate = Model.MinDate;
       st.Properties.MaxDate = DateTime.Today;
       st.Properties.AllowNull = true;
       st.ShowModelErrors = true;
       st.Properties.ValidationSettings.Display = Display.Dynamic;
       st.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
       st.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
       st.Properties.Caption = T("Ngày ra viện");
       st.Properties.DateRangeSettings.StartDateEditID = "DateIn" + suffix;
    }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-auto_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 96 "..\..\Views\Medical\FacilityProcess.cshtml"
    Write(Html.DevExpress().ComboBoxFor(m => m.Service, st =>
    {
       st.DefaultSettings();
       st.Name = "ProcessService" + suffix;
       st.Width = Unit.Percentage(100);
       st.Properties.Caption = T("Lĩnh vực can thiệp");
       st.Properties.TextField = "Name";
       st.Properties.ValueField = "Oid";
       st.Properties.ValueType = typeof(int);
       st.Properties.CaptionSettings.RequiredMarkDisplayMode = EditorRequiredMarkMode.Required;
    }).BindList(Service.ComboboxData()).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-auto_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 109 "..\..\Views\Medical\FacilityProcess.cshtml"
    Write(Html.DevExpress().ComboBoxFor(m => m.Status, st =>
    {
       st.DefaultSettings();
       st.Name = "ProcessStatus" + suffix;
       st.Width = Unit.Percentage(100);
       st.Properties.Caption = T("Kết quả can thiệp");
       st.Properties.TextField = "Name";
       st.Properties.ValueField = "Oid";
       st.Properties.ValueType = typeof(int);
       st.Properties.CaptionSettings.RequiredMarkDisplayMode = EditorRequiredMarkMode.Required;
       st.Properties.ClientSideEvents.ValueChanged = "function() {WebApp.function.toggleProcessReason('" + suffix + "');}";
    }).BindList(WebModule.MCNV.Models.ProcessStatus.ComboboxData()).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-12\"");

WriteAttribute("processreason-suffix", Tuple.Create(" processreason-suffix=\"", 5619), Tuple.Create("\"", 5649)
            
            #line 122 "..\..\Views\Medical\FacilityProcess.cshtml"
, Tuple.Create(Tuple.Create("", 5642), Tuple.Create<System.Object, System.Int32>(suffix
            
            #line default
            #line hidden
, 5642), false)
);

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 123 "..\..\Views\Medical\FacilityProcess.cshtml"
    Write(Html.DevExpress().TextBoxFor(m => m.Reason, st =>
    {
       st.DefaultSettings();
       st.Name = "ProcessReason" + suffix;
       st.Properties.Caption = T("Lý do chưa đạt mục tiêu");
       st.Properties.CaptionSettings.RequiredMarkDisplayMode = EditorRequiredMarkMode.Required;
       st.Properties.ClientSideEvents.Init = "function() {WebApp.function.toggleProcessReason('" + suffix + "');}";
    }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 132 "..\..\Views\Medical\FacilityProcess.cshtml"
                     Write(Html.EditorFor(m => m.Doctors));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   </div>\r\n   <div>");

            
            #line 134 "..\..\Views\Medical\FacilityProcess.cshtml"
   Write(Html.EditorFor(m => m.Attachments));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"grid-noBottom-noGutter mt\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-auto\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 137 "..\..\Views\Medical\FacilityProcess.cshtml"
    Write(Html.DevExpress().Button(btn =>
    {
       btn.Name = "FacilityProcessSave" + suffix;
       btn.Text = T("Lưu thay đổi");
       btn.Images.Image.IconID = IconID.SaveSave16x16;
       btn.Styles.Style.Paddings.Padding = 0;
       btn.RenderMode = ButtonRenderMode.Outline;
       btn.ClientVisible = false;
       btn.ControlStyle.CssClass = "mr";
       btn.ClientSideEvents.Click = "onFacilityProcessSave" + suffix;
    }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-auto\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 150 "..\..\Views\Medical\FacilityProcess.cshtml"
    Write(Html.DevExpress().Button(btn =>
    {
       btn.Name = "FacilityProcessDelete" + suffix;
       btn.Text = T("Xóa");
       btn.Images.Image.IconID = IconID.EditDelete16x16;
       btn.Styles.Style.Paddings.Padding = 0;
       btn.RenderMode = ButtonRenderMode.Outline;
       btn.ClientSideEvents.Click = "onFacilityProcessDelete" + suffix;
    }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n   </div>\r\n</form>");

        }
    }
}
#pragma warning restore 1591
