#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Medical/InfoProcess.cshtml")]
    public partial class _Views_Medical_InfoProcess_cshtml : WebApp.Core.BaseWebViewPage<InfoProcess>
    {
        public _Views_Medical_InfoProcess_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"dxss_infoprocess\"");

WriteLiteral(">\r\n   function onInfoProcessSave() {\r\n      if (!WebApp.validForm(\'#frmInfoProces" +
"s\')) return;\r\n      InfoProcessSave.SetEnabled(false);\r\n      WebApp.ajax(\'");

            
            #line 6 "..\..\Views\Medical\InfoProcess.cshtml"
              Write(Url.Action("InfoProcess", "Medical"));

            
            #line default
            #line hidden
WriteLiteral("\', getInfoData()).done(function (id) {\r\n         processModel.id = id;\r\n         " +
"processModel.reload();\r\n      }).fail(function () { InfoProcessSave.SetEnabled(t" +
"rue); });\r\n   }\r\n\r\n   function getInfoData() {\r\n");

            
            #line 13 "..\..\Views\Medical\InfoProcess.cshtml"
      
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Medical\InfoProcess.cshtml"
       if (Model.PatientFacilityEditable)
         {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n      return {\r\n         Id: ");

            
            #line 17 "..\..\Views\Medical\InfoProcess.cshtml"
         Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(",\r\n         Patient: Patient.GetValue(),\r\n         Facility: Facility.GetValue()," +
"\r\n      };\r\n            ");

WriteLiteral("\r\n");

            
            #line 22 "..\..\Views\Medical\InfoProcess.cshtml"
      }
      else
      {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n      return {\r\n         Id: processModel.id,\r\n         Code: Code.GetValue(),\r" +
"\n         Patient: ");

            
            #line 29 "..\..\Views\Medical\InfoProcess.cshtml"
              Write(Model.PatientFacilityEditable ? "Patient.GetValue()" : Model.Patient.ToString());

            
            #line default
            #line hidden
WriteLiteral(",\r\n         Facility: ");

            
            #line 30 "..\..\Views\Medical\InfoProcess.cshtml"
               Write(Model.PatientFacilityEditable ? "Facility.GetValue()" : Model.Facility.ToString());

            
            #line default
            #line hidden
WriteLiteral(",\r\n         Note: Note.GetValue(),\r\n      };\r\n            ");

WriteLiteral("\r\n");

            
            #line 34 "..\..\Views\Medical\InfoProcess.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("   }\r\n\r\n   setTimeout(function () {\r\n      WebApp.validateForm(\'#frmInfoProcess\')" +
";\r\n      var oldData = JSON.stringify(getInfoData());\r\n\r\n      const inps = [");

            
            #line 41 "..\..\Views\Medical\InfoProcess.cshtml"
                Write(Model.PatientFacilityEditable ? "Patient, Facility" : "Code, Note");

            
            #line default
            #line hidden
WriteLiteral("];\r\n      inps.forEach(function (it) {\r\n         it.ValueChanged.AddHandler(funct" +
"ion () {\r\n            var d = JSON.stringify(getInfoData());\r\n            InfoPr" +
"ocessSave.SetVisible(d != oldData);\r\n         });\r\n      });\r\n\r\n");

            
            #line 49 "..\..\Views\Medical\InfoProcess.cshtml"
      
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Medical\InfoProcess.cshtml"
       if (Model.PatientFacilityEditable)
      {

            
            #line default
            #line hidden
WriteLiteral("         ");

WriteLiteral("\r\n      Patient.ValueChanged.AddHandler(function (s) {\r\n         const id = s.Get" +
"Value();\r\n         if (!id) return;\r\n         WebApp.ajax(\'");

            
            #line 55 "..\..\Views\Medical\InfoProcess.cshtml"
                 Write(Url.Action("CheckPatientData", "Medical"));

            
            #line default
            #line hidden
WriteLiteral("\', { id: id }).done(function (r) {\r\n            if (r) return;\r\n            WebAp" +
"p.showInfo(\'");

            
            #line 57 "..\..\Views\Medical\InfoProcess.cshtml"
                        Write(H("Chú ý"));

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 57 "..\..\Views\Medical\InfoProcess.cshtml"
                                       Write(H("Bệnh nhân này được quản lý ở đơn vị khác mà bạn chưa được cấp quyền truy cập thông tin"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n         });\r\n      });\r\n         ");

WriteLiteral("\r\n");

            
            #line 61 "..\..\Views\Medical\InfoProcess.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("   });\r\n</script>\r\n\r\n<form");

WriteLiteral(" id=\"frmInfoProcess\"");

WriteLiteral(">\r\n");

WriteLiteral("   ");

            
            #line 66 "..\..\Views\Medical\InfoProcess.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 67 "..\..\Views\Medical\InfoProcess.cshtml"
   
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Medical\InfoProcess.cshtml"
    if (Model.PatientFacilityEditable)
   {

            
            #line default
            #line hidden
WriteLiteral("      <div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n         <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 70 "..\..\Views\Medical\InfoProcess.cshtml"
                        Write(T("Lưu ý: Phải kiểm tra Bệnh nhân, nếu đã có trên hệ thống thì không cần tạo mới."));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n         <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(">");

            
            #line 71 "..\..\Views\Medical\InfoProcess.cshtml"
                             Write(Html.EditorFor(m => m.Patient));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n         <div");

WriteLiteral(" class=\"col-6_xs-12\"");

WriteLiteral(">");

            
            #line 72 "..\..\Views\Medical\InfoProcess.cshtml"
                             Write(Html.EditorFor(m => m.Facility));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      </div>\r\n");

            
            #line 74 "..\..\Views\Medical\InfoProcess.cshtml"
   }
   else
   {

            
            #line default
            #line hidden
WriteLiteral("      <div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n         <div");

WriteLiteral(" class=\"col-2_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Medical\InfoProcess.cshtml"
                                  Write(Html.EditorFor(m => m.Code));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n         <div");

WriteLiteral(" class=\"col-2_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 79 "..\..\Views\Medical\InfoProcess.cshtml"
                                  Write(Html.LockedText(m => m.PatientCode));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n         <div");

WriteLiteral(" class=\"col-4_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 80 "..\..\Views\Medical\InfoProcess.cshtml"
                                  Write(Html.LockedText(m => m.PatientName));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 81 "..\..\Views\Medical\InfoProcess.cshtml"
         
            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\Medical\InfoProcess.cshtml"
          if (Model.CanAccessPatient)
         {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-2_md-3_xs-6\"");

WriteLiteral(">");

            
            #line 83 "..\..\Views\Medical\InfoProcess.cshtml"
                                    Write(Html.LockedText(m => m.PatientGender));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"col-2_md-3_xs-6\"");

WriteLiteral(">");

            
            #line 84 "..\..\Views\Medical\InfoProcess.cshtml"
                                    Write(Html.LockedText(m => m.PatientDateBirth));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 85 "..\..\Views\Medical\InfoProcess.cshtml"
                                Write(Html.LockedText(m => m.PatientPhone));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"col-8_xs-12\"");

WriteLiteral(">");

            
            #line 86 "..\..\Views\Medical\InfoProcess.cshtml"
                                Write(Html.LockedText(m => m.PatientAddress));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 87 "..\..\Views\Medical\InfoProcess.cshtml"
                                Write(Html.LockedText(m => m.PatientOrangeVictim));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 88 "..\..\Views\Medical\InfoProcess.cshtml"
                                Write(Html.LockedText(m => m.PatientClassification));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("            <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 89 "..\..\Views\Medical\InfoProcess.cshtml"
                                Write(Html.LockedText(m => m.PatientLevelDisability));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 90 "..\..\Views\Medical\InfoProcess.cshtml"
         }
         else
         {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"col-4_md-6_xs-12\"");

WriteLiteral(">\r\n               <span>");

            
            #line 94 "..\..\Views\Medical\InfoProcess.cshtml"
                Write(H("Thông tin NKT này được tạo bởi <b>{0}</b> và có thể đã điều trị, can thiệp tại đây. Để xem thông tin bạn cần gửi yêu cầu và chờ xác nhận.", Model.FacilityOfPatient));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n               <script");

WriteLiteral(" id=\"dxss_requestinfo\"");

WriteLiteral(">\r\n                  function onRequrestInfo(btn) {\r\n                     WebApp." +
"ajax(\'");

            
            #line 97 "..\..\Views\Medical\InfoProcess.cshtml"
                             Write(Url.Action("RequestPatientData", "Medical"));

            
            #line default
            #line hidden
WriteLiteral("\', { Id: ");

            
            #line 97 "..\..\Views\Medical\InfoProcess.cshtml"
                                                                                  Write(Model.Patient);

            
            #line default
            #line hidden
WriteLiteral("}).done(function () {\r\n                        btn.SetText(\'");

            
            #line 98 "..\..\Views\Medical\InfoProcess.cshtml"
                                Write(H("Chờ xác nhận"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n                        btn.SetEnabled(false);\r\n                     });\r\n  " +
"                }\r\n               </script>\r\n");

WriteLiteral("               ");

            
            #line 103 "..\..\Views\Medical\InfoProcess.cshtml"
          Write(Html.DevExpress().Button(st =>
          {
             st.Name = "btnRequestInfo";
             st.Text = Model.HasRequestPatient ? T("Chờ xác nhận") : T("Gửi yêu cầu");
             st.ClientEnabled = !Model.HasRequestPatient;
             st.Images.Image.IconID = IconID.MailNewcontact16x16;
             st.Styles.Style.Paddings.Padding = 0;
             st.ClientSideEvents.Click = "onRequrestInfo";
          }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 113 "..\..\Views\Medical\InfoProcess.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("      </div>\r\n");

WriteLiteral("      <div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n         <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 116 "..\..\Views\Medical\InfoProcess.cshtml"
                        Write(Html.LockedText(m => m.Disabilities));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      </div>\r\n");

WriteLiteral("      <div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n         <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 119 "..\..\Views\Medical\InfoProcess.cshtml"
                        Write(Html.LockedText(m => m.FacilityName));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      </div>\r\n");

WriteLiteral("      <div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n         <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 122 "..\..\Views\Medical\InfoProcess.cshtml"
                        Write(Html.EditorFor(m => m.Note));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      </div>\r\n");

            
            #line 124 "..\..\Views\Medical\InfoProcess.cshtml"
   }

            
            #line default
            #line hidden
WriteLiteral("   <div>\r\n");

WriteLiteral("      ");

            
            #line 126 "..\..\Views\Medical\InfoProcess.cshtml"
 Write(Html.DevExpress().Button(btn =>
   {
    btn.Name = "InfoProcessSave";
    btn.Text = T("Lưu thay đổi");
    btn.Images.Image.IconID = IconID.SaveSave16x16;
    btn.Styles.Style.Paddings.Padding = 0;
    btn.RenderMode = ButtonRenderMode.Outline;
    btn.ClientVisible = false;
    btn.ClientSideEvents.Click = "onInfoProcessSave";
   }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n   </div>\r\n</form>");

        }
    }
}
#pragma warning restore 1591
