#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Medical/StopProcess.cshtml")]
    public partial class _Views_Medical_StopProcess_cshtml : WebApp.Core.BaseWebViewPage<StopProcess>
    {
        public _Views_Medical_StopProcess_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"dxss_stopprocess\"");

WriteLiteral(">\r\n   function onStopProcessSave() {\r\n      if (!WebApp.validForm(\'#frmStopProces" +
"s\')) return;\r\n      StopProcessSave.SetEnabled(false);\r\n      WebApp.ajax(\'");

            
            #line 7 "..\..\Views\Medical\StopProcess.cshtml"
              Write(Url.Action("StopProcess", "Medical"));

            
            #line default
            #line hidden
WriteLiteral("\', getStopData()).done(function (r) {\r\n         processModel.reload();\r\n      })." +
"fail(function () { StopProcessSave.SetEnabled(true); });\r\n   }\r\n\r\n   function on" +
"StopProcessDelete() {\r\n      WebApp.showConfirm(\'");

            
            #line 13 "..\..\Views\Medical\StopProcess.cshtml"
                     Write(H("Xóa"));

            
            #line default
            #line hidden
WriteLiteral("\', \'");

            
            #line 13 "..\..\Views\Medical\StopProcess.cshtml"
                                  Write(H("Bạn có muốn xóa dữ liệu dừng can thiệp?"));

            
            #line default
            #line hidden
WriteLiteral("\').done(function () {\r\n         WebApp.ajax(\'");

            
            #line 14 "..\..\Views\Medical\StopProcess.cshtml"
                 Write(Url.Action("DeleteStopProcess", "Medical"));

            
            #line default
            #line hidden
WriteLiteral("\', { id: ");

            
            #line 14 "..\..\Views\Medical\StopProcess.cshtml"
                                                                     Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral(@"}).done(function () {
            processModel.reload();
         });
      });
   }

   function getStopData() {
      var d = CompletedDate.GetDate();
      return {
         Id: processModel.id,
         CompletedDate: d && d.toISOString() || null,
         ProcessCancel: ProcessCancel.GetValue(),
         Doctor: Doctor.GetValue(),
      };
   }

   setTimeout(function () {
      WebApp.validateForm('#frmStopProcess');
      var oldData = JSON.stringify(getStopData());

      [CompletedDate, ProcessCancel, Doctor].forEach(function (it) {
         it.ValueChanged.AddHandler(function () {
            var d = JSON.stringify(getStopData());
            StopProcessSave.SetVisible(d != oldData);
         });
      });
   });
</script>
<form");

WriteLiteral(" id=\"frmStopProcess\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-3_xs-12\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 45 "..\..\Views\Medical\StopProcess.cshtml"
    Write(Html.DevExpress().DateEditFor(m => m.CompletedDate, st =>
    {
       st.Width = Unit.Percentage(100);
       st.Properties.MinDate = Model.MinDate;
       st.Properties.MaxDate = DateTime.Today;
       st.Properties.AllowNull = false;
       st.ShowModelErrors = true;
       st.Properties.ValidationSettings.Display = Display.Dynamic;
       st.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
       st.Properties.CaptionSettings.RequiredMarkDisplayMode = EditorRequiredMarkMode.Required;
       st.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
       st.Properties.Caption = T("Ngày dừng can thiệp");
    }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-3_xs-12\"");

WriteLiteral(">");

            
            #line 59 "..\..\Views\Medical\StopProcess.cshtml"
                          Write(Html.EditorFor(m => m.ProcessCancel));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-3_xs-12\"");

WriteLiteral(">");

            
            #line 60 "..\..\Views\Medical\StopProcess.cshtml"
                          Write(Html.EditorFor(m => m.Doctor, new { Model.Doctors }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"grid-noBottom-noGutter\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-auto\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 64 "..\..\Views\Medical\StopProcess.cshtml"
    Write(Html.DevExpress().Button(btn =>
    {
       btn.Name = "StopProcessSave";
       btn.Text = T("Lưu thay đổi");
       btn.Images.Image.IconID = IconID.SaveSave16x16;
       btn.Styles.Style.Paddings.Padding = 0;
       btn.RenderMode = ButtonRenderMode.Outline;
       btn.ClientVisible = false;
       btn.ControlStyle.CssClass = "mr";
       btn.ClientSideEvents.Click = "onStopProcessSave";
    }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n      <div");

WriteLiteral(" class=\"col-auto\"");

WriteLiteral(">\r\n");

WriteLiteral("         ");

            
            #line 77 "..\..\Views\Medical\StopProcess.cshtml"
    Write(Html.DevExpress().Button(btn =>
    {
       btn.Name = "StopProcessDelete";
       btn.Text = T("Xóa");
       btn.Images.Image.IconID = IconID.EditDelete16x16;
       btn.Styles.Style.Paddings.Padding = 0;
       btn.RenderMode = ButtonRenderMode.Outline;
       btn.ClientSideEvents.Click = "onStopProcessDelete";
    }).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n      </div>\r\n   </div>\r\n</form>");

        }
    }
}
#pragma warning restore 1591
