//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebModule.MCNV.DataModel
{

   /// <summary>
   /// Vùng dự án
   /// </summary>
   public partial class Area : CompanyObject
   {
      string fCode;
      [ColumnDefaultValue("")]
      public string Code
      {
         get { return fCode; }
         set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
      }
      string fName;
      [ColumnDefaultValue("")]
      public string Name
      {
         get { return fName; }
         set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
      }
      string fNote;
      [Size(SizeAttribute.Unlimited)]
      [ColumnDefaultValue("")]
      public string Note
      {
         get { return fNote; }
         set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
      }
      [ExplicitLoading(1)]
      [Association(@"AreaProvinces", UseAssociationNameAsIntermediateTableName = true)]
      public XPCollection<Province> Provinces { get { return GetCollection<Province>(nameof(Provinces)); } }
   }

}
