//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebModule.MCNV.DataModel
{

    /// <summary>
    /// Hình ảnh, video kèm theo
    /// </summary>
    public partial class Attachment : CompanyObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fFileUrl;
        public string FileUrl
        {
            get { return fFileUrl; }
            set { SetPropertyValue<string>(nameof(FileUrl), ref fFileUrl, value); }
        }
        string fUniqueId;
        [Indexed(Name = @"IndexUniqueId")]
        public string UniqueId
        {
            get { return fUniqueId; }
            set { SetPropertyValue<string>(nameof(UniqueId), ref fUniqueId, value); }
        }
        [Association(@"MedicalEvaluationAttachments", UseAssociationNameAsIntermediateTableName = true)]
        public XPCollection<Medical> MedicalEvaluations { get { return GetCollection<Medical>(nameof(MedicalEvaluations)); } }
        [Association(@"MedicalCompletedAttachments", UseAssociationNameAsIntermediateTableName = true)]
        public XPCollection<Medical> MedicalCompleted { get { return GetCollection<Medical>(nameof(MedicalCompleted)); } }
        [Association(@"MedicalPlanAttachments", UseAssociationNameAsIntermediateTableName = true)]
        public XPCollection<Medical> MedicalPlan { get { return GetCollection<Medical>(nameof(MedicalPlan)); } }
        [Association(@"MedicalProcessAttachments", UseAssociationNameAsIntermediateTableName = true)]
        public XPCollection<MedicalProcess> MedicalProcesses { get { return GetCollection<MedicalProcess>(nameof(MedicalProcesses)); } }
        [Association(@"ProgramAttachments", UseAssociationNameAsIntermediateTableName = true)]
        public XPCollection<Program> Programs { get { return GetCollection<Program>(nameof(Programs)); } }
    }

}
