//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebModule.MCNV.DataModel
{

    /// <summary>
    /// Quận huyện
    /// </summary>
    public partial class District : XPLiteObject
    {
        int fOid;
        [Key]
        public int Oid
        {
            get { return fOid; }
            set { SetPropertyValue<int>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Province fProvince;
        [Association(@"DistrictReferencesProvince")]
        public Province Province
        {
            get { return fProvince; }
            set { SetPropertyValue<Province>(nameof(Province), ref fProvince, value); }
        }
        [Association(@"WardsReferencesDistrict"), Aggregated]
        public XPCollection<Ward> Wards { get { return GetCollection<Ward>(nameof(Wards)); } }
    }

}
