//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebModule.MCNV.DataModel
{

   /// <summary>
   /// Hồ sơ các lần can thiệp, điều trị
   /// </summary>
   public partial class MedicalProcess : CompanyObject
   {
      DateTime fProcessDate;
      public DateTime ProcessDate
      {
         get { return fProcessDate; }
         set { SetPropertyValue<DateTime>(nameof(ProcessDate), ref fProcessDate, value); }
      }
      ProcessStatus fStatus;
      public ProcessStatus Status
      {
         get { return fStatus; }
         set { SetPropertyValue<ProcessStatus>(nameof(Status), ref fStatus, value); }
      }
      Medical fMedical;
      [Association(@"MedicalProcessReferencesMedical")]
      public Medical Medical
      {
         get { return fMedical; }
         set { SetPropertyValue<Medical>(nameof(Medical), ref fMedical, value); }
      }
      Service fService;
      public Service Service
      {
         get { return fService; }
         set { SetPropertyValue<Service>(nameof(Service), ref fService, value); }
      }
      string fReason;
      [Size(SizeAttribute.Unlimited)]
      public string Reason
      {
         get { return fReason; }
         set { SetPropertyValue<string>(nameof(Reason), ref fReason, value); }
      }
      bool fValidData;
      public bool ValidData
      {
         get { return fValidData; }
         set { SetPropertyValue<bool>(nameof(ValidData), ref fValidData, value); }
      }
      bool fAtFacility;
      public bool AtFacility
      {
         get { return fAtFacility; }
         set { SetPropertyValue<bool>(nameof(AtFacility), ref fAtFacility, value); }
      }
      DateTime fDateIn;
      public DateTime DateIn
      {
         get { return fDateIn; }
         set { SetPropertyValue<DateTime>(nameof(DateIn), ref fDateIn, value); }
      }
      DateTime? fDateOut;
      public DateTime? DateOut
      {
         get { return fDateOut; }
         set { SetPropertyValue<DateTime?>(nameof(DateOut), ref fDateOut, value); }
      }
      int fProcessInd;
      public int ProcessInd
      {
         get { return fProcessInd; }
         set { SetPropertyValue<int>(nameof(ProcessInd), ref fProcessInd, value); }
      }
      [Association(@"MedicalProcessAttachments", UseAssociationNameAsIntermediateTableName = true)]
      public XPCollection<Attachment> Attachments { get { return GetCollection<Attachment>(nameof(Attachments)); } }
      [Association(@"MedicalProcessDoctors", UseAssociationNameAsIntermediateTableName = true)]
      public XPCollection<Doctor> Doctors { get { return GetCollection<Doctor>(nameof(Doctors)); } }
   }

}
