//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebModule.MCNV.DataModel
{

    /// <summary>
    /// Thông tin NKT
    /// </summary>
    public partial class Patient : CompanyObject
    {
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        [ColumnDefaultValue("")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Gender fGender;
        [ExplicitLoading(1)]
        public Gender Gender
        {
            get { return fGender; }
            set { SetPropertyValue<Gender>(nameof(Gender), ref fGender, value); }
        }
        Folk fFolk;
        public Folk Folk
        {
            get { return fFolk; }
            set { SetPropertyValue<Folk>(nameof(Folk), ref fFolk, value); }
        }
        DateTime fDateBirth;
        public DateTime DateBirth
        {
            get { return fDateBirth; }
            set { SetPropertyValue<DateTime>(nameof(DateBirth), ref fDateBirth, value); }
        }
        string fAddress;
        [ColumnDefaultValue("")]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fPhone;
        [ColumnDefaultValue("")]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        Classification fClassification;
        [ExplicitLoading(2)]
        public Classification Classification
        {
            get { return fClassification; }
            set { SetPropertyValue<Classification>(nameof(Classification), ref fClassification, value); }
        }
        LevelDisability fLevelDisability;
        [ExplicitLoading(2)]
        public LevelDisability LevelDisability
        {
            get { return fLevelDisability; }
            set { SetPropertyValue<LevelDisability>(nameof(LevelDisability), ref fLevelDisability, value); }
        }
        OrangeVictim fOrangeVictim;
        [ExplicitLoading(2)]
        public OrangeVictim OrangeVictim
        {
            get { return fOrangeVictim; }
            set { SetPropertyValue<OrangeVictim>(nameof(OrangeVictim), ref fOrangeVictim, value); }
        }
        Province fProvince;
        [ExplicitLoading(1)]
        public Province Province
        {
            get { return fProvince; }
            set { SetPropertyValue<Province>(nameof(Province), ref fProvince, value); }
        }
        District fDistrict;
        [ExplicitLoading(1)]
        public District District
        {
            get { return fDistrict; }
            set { SetPropertyValue<District>(nameof(District), ref fDistrict, value); }
        }
        Ward fWard;
        [ExplicitLoading(1)]
        public Ward Ward
        {
            get { return fWard; }
            set { SetPropertyValue<Ward>(nameof(Ward), ref fWard, value); }
        }
        string fNote;
        [Size(SizeAttribute.Unlimited)]
        [ColumnDefaultValue("")]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        string fCMND;
        public string CMND
        {
            get { return fCMND; }
            set { SetPropertyValue<string>(nameof(CMND), ref fCMND, value); }
        }
        string fCCCD;
        public string CCCD
        {
            get { return fCCCD; }
            set { SetPropertyValue<string>(nameof(CCCD), ref fCCCD, value); }
        }
        string fBHYT;
        public string BHYT
        {
            get { return fBHYT; }
            set { SetPropertyValue<string>(nameof(BHYT), ref fBHYT, value); }
        }
        int fAge;
        public int Age
        {
            get { return fAge; }
            set { SetPropertyValue<int>(nameof(Age), ref fAge, value); }
        }
        Area fArea;
        public Area Area
        {
            get { return fArea; }
            set { SetPropertyValue<Area>(nameof(Area), ref fArea, value); }
        }
        Facility fFacility;
        [ExplicitLoading(1)]
        public Facility Facility
        {
            get { return fFacility; }
            set { SetPropertyValue<Facility>(nameof(Facility), ref fFacility, value); }
        }
        string fDisabilitiesStr;
        [Size(SizeAttribute.Unlimited)]
        public string DisabilitiesStr
        {
            get { return fDisabilitiesStr; }
            set { SetPropertyValue<string>(nameof(DisabilitiesStr), ref fDisabilitiesStr, value); }
        }
        [ExplicitLoading(1)]
        [Association(@"PatientDisability", UseAssociationNameAsIntermediateTableName = true)]
        public XPCollection<Disability> Disabilities { get { return GetCollection<Disability>(nameof(Disabilities)); } }
    }

}
