//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebModule.MCNV.DataModel
{

   /// <summary>
   /// Kết quả điều trị
   /// </summary>
   public partial class ProcessStatus : XPObject
   {
      string fName;
      public string Name
      {
         get { return fName; }
         set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
      }
      int fOrderIndex;
      public int OrderIndex
      {
         get { return fOrderIndex; }
         set { SetPropertyValue<int>(nameof(OrderIndex), ref fOrderIndex, value); }
      }
   }

}
