//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebModule.MCNV.DataModel
{

   public partial class ProgramDoctor : XPObject
   {
      Doctor fDoctor;
      public Doctor Doctor
      {
         get { return fDoctor; }
         set { SetPropertyValue<Doctor>(nameof(Doctor), ref fDoctor, value); }
      }
      string fReasonCancel;
      public string ReasonCancel
      {
         get { return fReasonCancel; }
         set { SetPropertyValue<string>(nameof(ReasonCancel), ref fReasonCancel, value); }
      }
      Program fProgram;
      [Association(@"ProgramDoctorReferencesProgram")]
      public Program Program
      {
         get { return fProgram; }
         set { SetPropertyValue<Program>(nameof(Program), ref fProgram, value); }
      }
      TrainingStatus fStatus;
      public TrainingStatus Status
      {
         get { return fStatus; }
         set { SetPropertyValue<TrainingStatus>(nameof(Status), ref fStatus, value); }
      }
      decimal? fScore1;
      public decimal? Score1
      {
         get { return fScore1; }
         set { SetPropertyValue<decimal?>(nameof(Score1), ref fScore1, value); }
      }
      decimal? fScore2;
      public decimal? Score2
      {
         get { return fScore2; }
         set { SetPropertyValue<decimal?>(nameof(Score2), ref fScore2, value); }
      }
      decimal? fScore3;
      public decimal? Score3
      {
         get { return fScore3; }
         set { SetPropertyValue<decimal?>(nameof(Score3), ref fScore3, value); }
      }
      decimal? fScore4;
      public decimal? Score4
      {
         get { return fScore4; }
         set { SetPropertyValue<decimal?>(nameof(Score4), ref fScore4, value); }
      }
      decimal? fScore5;
      public decimal? Score5
      {
         get { return fScore5; }
         set { SetPropertyValue<decimal?>(nameof(Score5), ref fScore5, value); }
      }
      decimal? fScore6;
      public decimal? Score6
      {
         get { return fScore6; }
         set { SetPropertyValue<decimal?>(nameof(Score6), ref fScore6, value); }
      }
      decimal? fScore7;
      public decimal? Score7
      {
         get { return fScore7; }
         set { SetPropertyValue<decimal?>(nameof(Score7), ref fScore7, value); }
      }
      decimal? fScore8;
      public decimal? Score8
      {
         get { return fScore8; }
         set { SetPropertyValue<decimal?>(nameof(Score8), ref fScore8, value); }
      }
      decimal? fScore9;
      public decimal? Score9
      {
         get { return fScore9; }
         set { SetPropertyValue<decimal?>(nameof(Score9), ref fScore9, value); }
      }
      decimal? fScore10;
      public decimal? Score10
      {
         get { return fScore10; }
         set { SetPropertyValue<decimal?>(nameof(Score10), ref fScore10, value); }
      }
      decimal? fScore11;
      public decimal? Score11
      {
         get { return fScore11; }
         set { SetPropertyValue<decimal?>(nameof(Score11), ref fScore11, value); }
      }
      decimal? fScore12;
      public decimal? Score12
      {
         get { return fScore12; }
         set { SetPropertyValue<decimal?>(nameof(Score12), ref fScore12, value); }
      }
      decimal? fScore13;
      public decimal? Score13
      {
         get { return fScore13; }
         set { SetPropertyValue<decimal?>(nameof(Score13), ref fScore13, value); }
      }
      decimal? fScore14;
      public decimal? Score14
      {
         get { return fScore14; }
         set { SetPropertyValue<decimal?>(nameof(Score14), ref fScore14, value); }
      }
      decimal? fScore15;
      public decimal? Score15
      {
         get { return fScore15; }
         set { SetPropertyValue<decimal?>(nameof(Score15), ref fScore15, value); }
      }
      decimal? fScore16;
      public decimal? Score16
      {
         get { return fScore16; }
         set { SetPropertyValue<decimal?>(nameof(Score16), ref fScore16, value); }
      }
   }

}
