#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/ChangePassword.cshtml")]
    public partial class _Views_Home_ChangePassword_cshtml : WebApp.Core.BaseWebViewPage<WebApp.Models.ChangePassword>
    {
        public _Views_Home_ChangePassword_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"mb\"");

WriteLiteral(">\r\n");

WriteLiteral("   ");

            
            #line 3 "..\..\Views\Home\ChangePassword.cshtml"
Write(Html.EditorFor(m => m.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"mb\"");

WriteLiteral(">\r\n");

WriteLiteral("   ");

            
            #line 6 "..\..\Views\Home\ChangePassword.cshtml"
Write(Html.EditorFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div>\r\n");

WriteLiteral("   ");

            
            #line 9 "..\..\Views\Home\ChangePassword.cshtml"
Write(Html.EditorFor(m => m.Verify));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
