#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/MainMenu.cshtml")]
    public partial class _Views_Home_MainMenu_cshtml : WebApp.Core.BaseWebViewPage<Home>
    {
        public _Views_Home_MainMenu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
   function mainMenuItemClick(s, e) {
      if (e.item.name == ""skinGallery"" && e.parameter)
         WebApp.changeSkin(e.parameter);
      else if (e.item.name && e.item.name.startsWith('/')) {
         s.SetActiveTabIndex(s.GetActiveTab().index);
         WebApp.openMenu(e.item.name);
      }
   }
</script>
");

            
            #line 12 "..\..\Views\Home\MainMenu.cshtml"
 if (Model.HasHelp)
{

            
            #line default
            #line hidden
WriteLiteral("   <style>\r\n      ");

WriteLiteral(@"@media (min-width: 1200px) {
         .dxr-tabWrapper {
            background-image: url(/styles/images/logo_large.png);
            background-repeat: no-repeat;
            background-position: 98% 85%;
            width: 100% !important;
         }
      }
   </style>
");

            
            #line 24 "..\..\Views\Home\MainMenu.cshtml"
}

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Home\MainMenu.cshtml"
Write(Html.DevExpress().Ribbon(st =>
{
   st.Name = "ribbonMainMenu";
   st.Width = Unit.Percentage(100);
   var cook = Request.Cookies["mainmenuMinimized"];
   st.Minimized = cook == null ? false : Convert.ToBoolean(cook.Value);

   //tab Functions
   foreach (var tab in Model.MainMenu)
   {
      var t = st.Tabs.Add(T(tab.Name));
      t.Name = tab.Name;
      foreach (var group in tab.Groups)
      {
         var g = t.Groups.Add(T(group.Name));
         g.Name = group.Name;
         if (!string.IsNullOrEmpty(group.Image))
            g.Image.SpriteProperties.CssClass = "img " + group.Image;
         else if (!string.IsNullOrEmpty(group.Icon))
            g.Image.IconID = group.Icon;
         foreach (var item in group.Functions)
         {
            var it = g.Items.Add(MVCxRibbonItemType.ButtonItem, item.Url, T(item.Name)) as RibbonButtonItem;
            it.Size = RibbonItemSize.Large;
            if (!string.IsNullOrEmpty(item.Image))
               it.LargeImage.SpriteProperties.CssClass = "img " + item.Image;
            else if (!string.IsNullOrEmpty(item.Icon))
               it.LargeImage.IconID = item.Icon;
         }
      }
   }

   //tab Options
   var tabOptions = (MVCxRibbonTab)st.Tabs.FirstOrDefault(p => p.Name == T("Cấu hình"));
   if (tabOptions == null)
      tabOptions = st.Tabs.Add(T("Cấu hình"));

   if (Model.SelectCompany)
   {
      var gData = tabOptions.Groups.Add("");
      var data = (RibbonButtonItem)gData.Items.Add(MVCxRibbonItemType.ButtonItem, "selectCompany", T("Chọn dữ liệu"));
      data.NavigateUrl = "javascript:WebApp.selectCompany()";
      data.Size = RibbonItemSize.Large;
      data.LargeImage.IconID = IconID.DataDatabase32x32;
   }

   var gUser = tabOptions.Groups.Add(T("Người dùng"));
   gUser.Image.IconID= IconID.ViewCard32x32devav;
   var profile = (RibbonButtonItem)gUser.Items.Add(MVCxRibbonItemType.ButtonItem, "/Home/UpdateProfile", T("Thông tin"));
   profile.Size = RibbonItemSize.Large;
   profile.LargeImage.IconID = IconID.ViewCard32x32devav;

   var changePW = (RibbonButtonItem)gUser.Items.Add(MVCxRibbonItemType.ButtonItem, "changePassword", T("Đổi mật khẩu"));
   changePW.NavigateUrl = "javascript:WebApp.changePassword()";
   changePW.Size = RibbonItemSize.Large;
   changePW.LargeImage.IconID = IconID.BusinessobjectsBopermission32x32;

   var gSkin = tabOptions.Groups.Add(T("Giao diện"));
   gSkin.Image.IconID = IconID.XafActionChooseskin32x32;
   var skins = (RibbonGalleryBarItem)gSkin.Items.Add(MVCxRibbonItemType.GalleryBarItem, "skinGallery");
   skins.Value = Model.SkinCurrent;
   skins.ValueType = typeof(string);
   skins.ImageHeight = 24;
   skins.ImageWidth = 72;
   skins.ShowText = false;
   skins.MinColumnCount = 3;
   skins.MaxColumnCount = 3;
   skins.RowCount = 2;
   skins.PropertiesDropDownGallery.RowCount = 7;
   foreach (var g in Model.Skins)
   {
      var skinGroup = skins.Groups.Add(T(g.Key));
      foreach (var s in g.Value)
      {
         var it = new RibbonGalleryItem();
         it.Image.SpriteProperties.CssClass = "img skin_" + s.ToLower();
         it.Value = s;
         skinGroup.Items.Add(it);
      }
   }

   if (Model.Languages.Count > 1)
   {
      var gLang = tabOptions.Groups.Add(T("Ngôn ngữ"));
      foreach (var l in Model.Languages)
      {
         var it = gLang.Items.Add(MVCxRibbonItemType.ToggleButtonItem, "Language_" + l.Code, l.Name) as RibbonToggleButtonItem;
         it.Size = RibbonItemSize.Large;
         it.LargeImage.SpriteProperties.CssClass = "img " + l.Code;
         if (l.Code == Model.LanguageCurrent)
         {
            it.Checked = true;
            it.ClientEnabled = false;
         }
         else
            it.NavigateUrl = "javascript:WebApp.changeLanguage('" + l.Code + "')";
      }
   }

   var groupExit = tabOptions.Groups.Add(T(""));
   if (Model.HasHelp)
   {
      var btnHelp = groupExit.Items.Add(MVCxRibbonItemType.ButtonItem, "help", T("Hướng dẫn")) as RibbonButtonItem;
      btnHelp.Size = RibbonItemSize.Large;
      btnHelp.LargeImage.IconID = IconID.SupportQuestion32x32;
      btnHelp.NavigateUrl = "javascript:WebApp.help()";
   }
   var btnExit = groupExit.Items.Add(MVCxRibbonItemType.ButtonItem, "exit", T("Thoát")) as RibbonButtonItem;
   btnExit.Size = RibbonItemSize.Large;
   btnExit.LargeImage.SpriteProperties.CssClass = "img exit";
   btnExit.NavigateUrl = "javascript:WebApp.exit()";



   st.ClientSideEvents.CommandExecuted = "mainMenuItemClick";
   st.ClientSideEvents.MinimizationStateChanged = "function(s,e) {WebApp.resize();ASPx.Cookie.SetCookie('mainmenuMinimized',s.GetMinimized());}";
   st.ShowFileTab = true;
   st.SetFileTabTemplateContent(c =>
   {
      if (Model.HasHelp)
      {
         ViewContext.Writer.WriteLine("<div style='height: 100%;display: flex;justify-content: center;align-items: center;padding: 0 5px;'><img src='/styles/images/logo.png' style='max-height: 20px;' onclick='WebApp.help()' /></div>");
      }
      else
      {
         ViewContext.Writer.WriteLine("<div class='pl pr dxtc-link'>");
         ViewContext.Writer.WriteLine(Html.Icon(IconID.PeopleEmployee16x16));
         ViewContext.Writer.WriteLine("<span class='dx-vam'>" + User.Identity.Name + "</span>");
         ViewContext.Writer.WriteLine("</div>");
      }
   });
}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
