#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 2 "..\..\Views\Home\Preview.cshtml"
    using DevExpress.XtraReports.Web;
    
    #line default
    #line hidden
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Preview.cshtml")]
    public partial class _Views_Home_Preview_cshtml : WebApp.Core.BaseWebViewPage<WebApp.Core.ReportInfo>
    {
        public _Views_Home_Preview_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Home\Preview.cshtml"
Write(Html.DevExpress().DocumentViewer(st =>
{
   st.Name = "documentViewer";
   st.Width = Unit.Percentage(100);
   st.Height = 300;
   var it = new ReportToolbarButton();
   it.Name = "designer";
   it.Text = T("Thiết kế");
   it.IconID = IconID.ReportsDesignreport16x16;
   st.ToolbarItems.Add(it);
   it = new ReportToolbarButton();
   it.Name = "close";
   it.Text = T("Đóng");
   it.IconID = IconID.ActionsClose16x16;
   st.ToolbarItems.Add(it);
   st.CustomJSProperties = (s, e) =>
   {
      if (Model != null && Model.Id != 0)
      {
         e.Properties["cpReportId"] = Model.Id;
         e.Properties["cpDesigner"] = CheckPermission("Mẫu báo cáo", "Thiết kế mẫu");
      }
   };
   st.SettingsReportViewer.EnableReportMargins = true;
   if (Model != null && Model.Report != null)
      st.Report = Model.Report;
   st.CallbackRouteValues = new { Action = "Preview" };
   st.ExportRouteValues = new { Action = "Export" };
   st.ClientSideEvents.ToolbarItemClick = "function(s,e) {if (e.item.name=='close') popupPreview.Hide(); else if (e.item.name=='designer') window.open('" + Url.Action("Designer", "Report") + "/' + s.cpReportId,'_blank');}";
   st.ClientSideEvents.EndCallback = "function(s,e) {s.GetToolbar().menu.GetItemByName('designer').SetVisible(s.cpDesigner);}";
}).GetHtml());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
