#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Online/IndexPartial.cshtml")]
    public partial class _Views_Online_IndexPartial_cshtml : WebApp.Core.BaseWebViewPage<List<Online>>
    {
        public _Views_Online_IndexPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Online\IndexPartial.cshtml"
Write(Html.DevExpress().GridView(st =>
{
   st.Name = "grdSheet";
   st.Width = Unit.Percentage(100);
   st.Settings.VerticalScrollBarMode = ScrollBarMode.Auto;
   st.SettingsPager.PageSize = 50;
   st.CallbackRouteValues = new { Action = "IndexPartial" };
   st.KeyFieldName = "Id";
   st.SettingsBehavior.AutoExpandAllGroups = true;
   st.Settings.GroupFormat = "{1}";

   st.Toolbars.Add(toolbar =>
   {
      toolbar.Name = "toolbarMain";
      toolbar.Enabled = true;
      toolbar.Position = GridToolbarPosition.Top;
      toolbar.ItemAlign = GridToolbarItemAlign.Left;
      toolbar.EnableAdaptivity = true;
      toolbar.Items.Add(tool =>
      {
         tool.Text = T("Làm mới");
         tool.ToolTip = T("Làm mới dữ liệu (F5)");
         tool.Image.IconID = IconID.ActionsRefresh16x16;
         tool.Command = GridViewToolbarCommand.Refresh;
      });
      toolbar.Items.Add(tool =>
      {
         tool.Name = "close";
         tool.Text = T("Đóng");
         tool.Image.IconID = IconID.ActionsClose16x16;
         tool.ToolTip = T("Đóng chức năng này (ESC)");
         tool.Command = GridViewToolbarCommand.Custom;
         tool.BeginGroup = true;
      });
   });

   st.Columns.Add(col =>
   {
      col.FieldName = "Company";
      col.Caption = T("Công ty");
      col.GroupIndex = 0;
   });

   st.Columns.Add("UserName", T("Tên đăng nhập"));
   st.Columns.Add("FullName", T("Tên người dùng"));
   st.Columns.Add("Phone", T("Điện thoại"));

   st.ClientSideEvents.ToolbarItemClick = "function(s,e) {e.item.name && WebApp.function[e.item.name] && WebApp.function[e.item.name].apply(WebApp);}";
}).Bind(Model).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
