#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/HomePage.cshtml")]
    public partial class _Views_Shared_HomePage_cshtml : WebApp.Core.BaseWebViewPage<dynamic>
    {
        public _Views_Shared_HomePage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<style>
   .homepage {
      height: 100%;
      display: flex;
      flex-direction: column;
      background: url(""/Styles/images/bg/login.jpeg?v=1"") 50% fixed;
      background-size: cover;
      align-items: center;
      justify-content: center;
   }

   .text3, .text4 {
      display: none;
   }

   .text1 {
      text-align: center;
   }

      .text1 span {
         padding: 10px 20px;
         background-color: rgba(255,255,255,0.2);
         line-height: 60px;
         font-size: 32px;
         font-weight: bold;
         color: #fff;
         border-radius: 24px;
      }

   .text2 {
      margin-top: 30px;
      padding: 10px 20px;
      background-color: #fff;
      font-size: 24px;
      font-weight: bold;
      border-radius: 24px;
      color: #555;
   }

   .text3 {
      text-align: center;
      font-size: 24px;
      font-weight: bold;
      color: #fff;
      padding: 10px;
   }

   .text4 {
      margin-top: 20px;
      font-weight: bold;
      color: #fff;
      text-align: center;
   }

   ");

WriteLiteral("@media (max-width: 600px) {\r\n      .text1, .text2 {\r\n         display: none;\r\n   " +
"   }\r\n\r\n      .text3, .text4 {\r\n         display: block;\r\n      }\r\n   }\r\n</style" +
">\r\n<div");

WriteLiteral(" class=\"homepage\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"text1\"");

WriteLiteral(">\r\n      <span>");

            
            #line 67 "..\..\Views\Shared\HomePage.cshtml"
       Write(H("HỆ THỐNG LƯU TRỮ DỮ LIỆU"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n      <br />\r\n      <span>");

            
            #line 69 "..\..\Views\Shared\HomePage.cshtml"
       Write(H("CÁC THÔNG TIN CÁ NHÂN & SỨC KHỎE CỦA NGƯỜI KHUYẾT TẬT"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"text2\"");

WriteLiteral(">\r\n      <span>");

            
            #line 72 "..\..\Views\Shared\HomePage.cshtml"
       Write(H("Đơn vị quản lý:"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n      <span>");

            
            #line 73 "..\..\Views\Shared\HomePage.cshtml"
       Write(H("Ủy ban Y tế Hà Lan - Việt Nam (MCNV)"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"text3\"");

WriteLiteral(">\r\n      <span>");

            
            #line 76 "..\..\Views\Shared\HomePage.cshtml"
       Write(H("HỆ THỐNG LƯU TRỮ DỮ LIỆU VỀ CÁC THÔNG TIN CÁ NHÂN VÀ SỨC KHỎE CỦA NGƯỜI KHUYẾT TẬT"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"text4\"");

WriteLiteral(">\r\n      <span>");

            
            #line 79 "..\..\Views\Shared\HomePage.cshtml"
       Write(H("Đơn vị quản lý:"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n      <br />\r\n      <span>");

            
            #line 81 "..\..\Views\Shared\HomePage.cshtml"
       Write(H("Ủy ban Y tế Hà Lan - Việt Nam (MCNV)"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n   </div>\r\n</div>\r\n<script>\r\n   WebApp.title = \'");

            
            #line 85 "..\..\Views\Shared\HomePage.cshtml"
              Write(H(Model.Name));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n   document.title = \'");

            
            #line 86 "..\..\Views\Shared\HomePage.cshtml"
                Write(H("Trang chủ"));

            
            #line default
            #line hidden
WriteLiteral(" | \' + WebApp.title;\r\n</script>");

        }
    }
}
#pragma warning restore 1591
