#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/AttachmentsLocked.cshtml")]
    public partial class _Views_Shared_EditorTemplates_AttachmentsLocked_cshtml_ : WebApp.Core.BaseWebViewPage<Attachments>
    {
        public _Views_Shared_EditorTemplates_AttachmentsLocked_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\AttachmentsLocked.cshtml"
 if (Model.Items.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("   <script>\r\n   function downloadAttachment");

            
            #line 5 "..\..\Views\Shared\EditorTemplates\AttachmentsLocked.cshtml"
                          Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("(id, saveas) {\r\n      window.open(\'");

            
            #line 6 "..\..\Views\Shared\EditorTemplates\AttachmentsLocked.cshtml"
              Write(Url.Action("Viewer", "Attachment"));

            
            #line default
            #line hidden
WriteLiteral("/\' + id + \'?saveas=\' + saveas, \'_blank\');\r\n   }\r\n   </script>\r\n");

WriteLiteral("   <div>\r\n");

WriteLiteral("      ");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\AttachmentsLocked.cshtml"
 Write(Html.DevExpress().ListBox(st =>
 {
    st.Name = "ListAttachment" + Model.Name;
    st.Width = Unit.Percentage(100);
    st.Properties.Caption = T("Tài liệu, hình ảnh, video");
    st.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
    st.ReadOnly = true;
    st.Properties.Columns.Add(col =>
    {
       col.Width = 40;
       col.SetColumnCellTemplateContent(c =>
       {
          var type = (AttachmentType)c.EvalDataItem("Type");
          var icon = IconID.BusinessobjectsBofileattachment16x16;
          if (type == AttachmentType.Image)
          {
             icon = IconID.ContentImage16x16;
          }
          else if (type == AttachmentType.Video)
          {
             icon = IconID.MediaVideocontent16x16;
          }
          else if (type == AttachmentType.Audio)
          {
             icon = IconID.MediaAudiocontent16x16;
          }
          else if (type == AttachmentType.PDF)
          {
             icon = IconID.ExportExporttopdfSvg16x16;
          }
          ViewContext.Writer.Write(String.Format("<div style='cursor: pointer;display: inline-block;' onclick=\"downloadAttachment{0}('{1}', '{2}')\">", Model.Name, c.EvalDataItem("UniqueId"), c.EvalDataItem("SaveAs")));
          ViewContext.Writer.Write(Html.Icon(icon));
          ViewContext.Writer.Write("</div>");
       });
    });
    st.Properties.Columns.Add(col =>
    {
       col.FieldName = "DateCreate";
       col.Caption = T("Ngày tạo");
       col.Width = 100;
    });
    st.Properties.Columns.Add(col =>
    {
       col.FieldName = "UserCreate";
       col.Caption = T("Người tạo");
       col.Width = 120;
    });
    st.Properties.Columns.Add(col =>
    {
       col.FieldName = "Name";
       col.Caption = T("Tên tài liệu");
       col.Width = Unit.Percentage(100);
    });
    //auto height by content
    st.Properties.ClientSideEvents.Init = "function(s) {setTimeout(function() { s.SetHeight(s.GetHeightByContent()-1);});}";
 }).BindList(Model.Items).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n   </div>\r\n");

            
            #line 67 "..\..\Views\Shared\EditorTemplates\AttachmentsLocked.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
