#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Diagnostics.cshtml")]
    public partial class _Views_Shared_EditorTemplates_Diagnostics_cshtml_ : WebApp.Core.BaseWebViewPage<string>
    {
        public _Views_Shared_EditorTemplates_Diagnostics_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\EditorTemplates\Diagnostics.cshtml"
  
   var name = ViewData.ModelMetadata.PropertyName;
   var caption = T(ViewData.ModelMetadata.DisplayName);
   var ids = ViewData.ModelMetadata.ContainerType.GetProperty(name + "Value").GetValue(ViewData.ModelMetadata.Container) as string;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n   function onDiagnosticsChanged(s) {\r\n      const items = s.GetSel" +
"ectedItems();\r\n      const name = \'#");

            
            #line 12 "..\..\Views\Shared\EditorTemplates\Diagnostics.cshtml"
                 Write(name);

            
            #line default
            #line hidden
WriteLiteral("Value\';\r\n      $(name).val(items.map(it => it.value).join(\';\'));\r\n      const ctr" +
"l = ");

            
            #line 14 "..\..\Views\Shared\EditorTemplates\Diagnostics.cshtml"
              Write(name);

            
            #line default
            #line hidden
WriteLiteral(@";
      ctrl.SetValue(items.map(it => it.texts[1]).join('; '));
      ctrl.RaiseValueChanged();
   }
   function onDiagnosticsDropdown() {
      DiagnosticsList.SetHeight(DiagnosticsList.GetItemHeight() * 8);
   }
   function onNewDiagnostic() {
      WebApp.showDialog({
         title: '");

            
            #line 23 "..\..\Views\Shared\EditorTemplates\Diagnostics.cshtml"
            Write(H("Thêm chẩn đoán"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n         url: \'");

            
            #line 24 "..\..\Views\Shared\EditorTemplates\Diagnostics.cshtml"
          Write(Url.Action("Add", "Diagnostic"));

            
            #line default
            #line hidden
WriteLiteral(@"',
         width: 600,
      }).done(function (r) {
         const sel = DiagnosticsList.AddItem([r.Code, r.Name], r.Id);
         DiagnosticsList.SetSelectedIndex(sel);
         DiagnosticsList.RaiseSelectedIndexChanged();
      });
   }
</script>
<input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1126), Tuple.Create("\"", 1143)
            
            #line 33 "..\..\Views\Shared\EditorTemplates\Diagnostics.cshtml"
, Tuple.Create(Tuple.Create("", 1131), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 1131), false)
, Tuple.Create(Tuple.Create("", 1138), Tuple.Create("Value", 1138), true)
);

WriteAttribute("name", Tuple.Create(" name=\"", 1144), Tuple.Create("\"", 1163)
            
            #line 33 "..\..\Views\Shared\EditorTemplates\Diagnostics.cshtml"
, Tuple.Create(Tuple.Create("", 1151), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 1151), false)
, Tuple.Create(Tuple.Create("", 1158), Tuple.Create("Value", 1158), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1164), Tuple.Create("\"", 1176)
            
            #line 33 "..\..\Views\Shared\EditorTemplates\Diagnostics.cshtml"
, Tuple.Create(Tuple.Create("", 1172), Tuple.Create<System.Object, System.Int32>(ids
            
            #line default
            #line hidden
, 1172), false)
);

WriteLiteral(" />\r\n<style>\r\n   #DiagnosticsList td.dxeCM, #DiagnosticsList td.dxeHCC {\r\n      w" +
"idth: 20px !important;\r\n   }\r\n</style>\r\n");

            
            #line 39 "..\..\Views\Shared\EditorTemplates\Diagnostics.cshtml"
Write(Html.DevExpress().DropDownEditFor(m => m, dp =>
{
   dp.Width = Unit.Percentage(100);
   dp.Properties.Caption = T(caption);
   dp.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
   if (ViewData.ModelMetadata.IsRequired)
   {
      dp.Properties.CaptionSettings.RequiredMarkDisplayMode = EditorRequiredMarkMode.Required;
   }
   dp.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
   dp.Properties.ValidationSettings.Display = Display.Dynamic;
   dp.ShowModelErrors = true;
   dp.ReadOnly = true;
   dp.Properties.EnableClientSideAPI = true;
   dp.Properties.SettingsAdaptivity.Mode = DropDownEditAdaptivityMode.OnWindowInnerWidth;
   dp.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Never;
   dp.SetDropDownWindowTemplateContent(container =>
   {
      Html.DevExpress().ListBox(st =>
      {
         st.Name = "DiagnosticsList";
         st.Width = Unit.Percentage(100);
         st.Properties.SelectionMode = ListEditSelectionMode.CheckColumn;
         st.ControlStyle.Border.BorderWidth = 0;
         st.Properties.ValueField = "Oid";
         st.Properties.ValueType = typeof(int);
         st.Properties.Columns.Add("Code", T("Mã")).Width = 50;
         st.Properties.Columns.Add("Name", T("Tên"));
         st.Properties.TextField = "Name";
         st.Properties.FilteringSettings.ShowSearchUI = true;
         st.Properties.FilteringSettings.UseCompactView = false;
         st.Properties.EnableClientSideAPI = true;
         st.Properties.ClientSideEvents.SelectedIndexChanged = "onDiagnosticsChanged";
         st.PreRender += (sender, _) =>
         {
            var me = sender as MVCxListBox;
            if (!string.IsNullOrEmpty(ids))
            {
               var vals = ids.Split(';').Select(el => int.Parse(el)).ToList();
               foreach (ListEditItem it in me.Items)
               {
                  it.Selected = vals.Contains((int)it.Value);
               }
            }
         };
      }).BindList(Diagnostic.ComboboxData()).Render();
   });
   dp.Properties.ClientSideEvents.DropDown = "onDiagnosticsDropdown";
   if (CheckPermission("Chẩn đoán", "Thêm"))
   {
      var btn = dp.Properties.Buttons.Add();
      btn.Image.IconID = IconID.ActionsAdd16x16;
      btn.ToolTip = T("Thêm");
      dp.Properties.ClientSideEvents.ButtonClick = "onNewDiagnostic";
   }
}).GetHtml());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
