#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Services.cshtml")]
    public partial class _Views_Shared_EditorTemplates_Services_cshtml_ : WebApp.Core.BaseWebViewPage<string>
    {
        public _Views_Shared_EditorTemplates_Services_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\EditorTemplates\Services.cshtml"
  
   var name = ViewData.ModelMetadata.PropertyName;
   var caption = T(ViewData.ModelMetadata.DisplayName);
   var ids = ViewData.ModelMetadata.ContainerType.GetProperty(name + "Value").GetValue(ViewData.ModelMetadata.Container) as string;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n   function onServicesChanged(s) {\r\n      const items = s.GetSelect" +
"edItems();\r\n      const name = \'#");

            
            #line 12 "..\..\Views\Shared\EditorTemplates\Services.cshtml"
                 Write(name);

            
            #line default
            #line hidden
WriteLiteral("Value\';\r\n      $(name).val(items.map(it => it.value).join(\';\'));\r\n      const ctr" +
"l = ");

            
            #line 14 "..\..\Views\Shared\EditorTemplates\Services.cshtml"
              Write(name);

            
            #line default
            #line hidden
WriteLiteral(";\r\n      ctrl.SetValue(items.map(it => it.text).join(\'; \'));\r\n      ctrl.RaiseVal" +
"ueChanged();\r\n   }\r\n   function onServicesDropdown() {\r\n      const ctrl = ");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\Services.cshtml"
              Write(name);

            
            #line default
            #line hidden
WriteLiteral(";\r\n      ServicesList.SetHeight(ServicesList.GetHeightByContent() + 10);\r\n   }\r\n<" +
"/script>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("id", Tuple.Create(" id=\"", 747), Tuple.Create("\"", 764)
            
            #line 23 "..\..\Views\Shared\EditorTemplates\Services.cshtml"
, Tuple.Create(Tuple.Create("", 752), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 752), false)
, Tuple.Create(Tuple.Create("", 759), Tuple.Create("Value", 759), true)
);

WriteAttribute("name", Tuple.Create(" name=\"", 765), Tuple.Create("\"", 784)
            
            #line 23 "..\..\Views\Shared\EditorTemplates\Services.cshtml"
, Tuple.Create(Tuple.Create("", 772), Tuple.Create<System.Object, System.Int32>(name
            
            #line default
            #line hidden
, 772), false)
, Tuple.Create(Tuple.Create("", 779), Tuple.Create("Value", 779), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 785), Tuple.Create("\"", 797)
            
            #line 23 "..\..\Views\Shared\EditorTemplates\Services.cshtml"
, Tuple.Create(Tuple.Create("", 793), Tuple.Create<System.Object, System.Int32>(ids
            
            #line default
            #line hidden
, 793), false)
);

WriteLiteral(" />\r\n");

            
            #line 24 "..\..\Views\Shared\EditorTemplates\Services.cshtml"
Write(Html.DevExpress().DropDownEditFor(m => m, dp =>
{
   dp.Width = Unit.Percentage(100);
   dp.Properties.Caption = T(caption);
   dp.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
   if (ViewData.ModelMetadata.IsRequired)
   {
      dp.Properties.CaptionSettings.RequiredMarkDisplayMode = EditorRequiredMarkMode.Required;
   }
   dp.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithTooltip;
   dp.Properties.ValidationSettings.Display = Display.Dynamic;
   dp.ShowModelErrors = true;
   dp.ReadOnly = true;
   dp.Properties.EnableClientSideAPI = true;
   dp.Properties.SettingsAdaptivity.Mode = DropDownEditAdaptivityMode.OnWindowInnerWidth;
   dp.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Never;
   dp.SetDropDownWindowTemplateContent(container =>
   {
      Html.DevExpress().ListBox(st =>
      {
         st.Name = "ServicesList";
         st.Width = Unit.Percentage(100);
         st.Properties.SelectionMode = ListEditSelectionMode.CheckColumn;
         st.Properties.ValueField = "Oid";
         st.Properties.ValueType = typeof(int);
         st.Properties.TextField = "Name";
         st.ControlStyle.Border.BorderWidth = 0;
         st.Properties.EnableClientSideAPI = true;
         st.Properties.ClientSideEvents.SelectedIndexChanged = "onServicesChanged";
         st.PreRender += (sender, _) =>
         {
            var me = sender as MVCxListBox;
            if (!string.IsNullOrEmpty(ids))
            {
               var vals = ids.Split(';').Select(el => int.Parse(el)).ToList();
               foreach (ListEditItem it in me.Items)
               {
                  it.Selected = vals.Contains((int)it.Value);
               }
            }
         };
      }).BindList(Service.ComboboxData()).Render();
   });
   dp.Properties.ClientSideEvents.DropDown = "onServicesDropdown";
}).GetHtml());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
