#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/HomePage.cshtml")]
    public partial class _Views_Shared_HomePage_cshtml : WebApp.Core.BaseWebViewPage<CompanyInfo>
    {
        public _Views_Shared_HomePage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"grid-middle-center\"");

WriteLiteral(" style=\"height: 100%;\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(" style=\"text-align: center; padding: 50px;\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"companyName\"");

WriteLiteral(">");

            
            #line 4 "..\..\Views\Shared\HomePage.cshtml"
                          Write(Model.FullName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"companyAddress\"");

WriteLiteral(">");

            
            #line 5 "..\..\Views\Shared\HomePage.cshtml"
                             Write(Model.Address);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   </div>\r\n</div>\r\n\r\n<script>\r\n   WebApp.title = \'");

            
            #line 10 "..\..\Views\Shared\HomePage.cshtml"
              Write(H(Model.Name));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n   document.title = \'");

            
            #line 11 "..\..\Views\Shared\HomePage.cshtml"
                Write(H("Trang chủ"));

            
            #line default
            #line hidden
WriteLiteral(" | \' + WebApp.title;\r\n</script>");

        }
    }
}
#pragma warning restore 1591
