#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/EditTemplate.cshtml")]
    public partial class _Views_Report_EditTemplate_cshtml : WebApp.Core.BaseWebViewPage<Report>
    {
        public _Views_Report_EditTemplate_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Report\EditTemplate.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"mb\"");

WriteLiteral(">\r\n");

WriteLiteral("   ");

            
            #line 4 "..\..\Views\Report\EditTemplate.cshtml"
Write(Html.EditorFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"mb\"");

WriteLiteral(">\r\n");

WriteLiteral("   ");

            
            #line 7 "..\..\Views\Report\EditTemplate.cshtml"
Write(Html.DevExpress().ComboBoxFor(m => m.Category, st =>
{
   st.Width = Unit.Percentage(100);
   st.Properties.Caption = "Nhóm báo cáo";
   st.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
   st.ShowModelErrors = true;
   st.Properties.ValidationSettings.Display = Display.Dynamic;
   st.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
   st.Properties.IncrementalFilteringDelay = 200;
   st.Properties.DropDownStyle = DropDownStyle.DropDown;
   st.Properties.AllowNull = true;
}).BindList(Report.GetCategories()).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"mb\"");

WriteLiteral(">\r\n");

WriteLiteral("   ");

            
            #line 21 "..\..\Views\Report\EditTemplate.cshtml"
Write(Html.DevExpress().TokenBoxFor(m => m.Parameters, st =>
{
   st.Width = Unit.Percentage(100);
   st.Properties.Caption = T("Tham số");
   st.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
   st.Properties.AllowCustomTokens = false;
   st.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
   st.Properties.IncrementalFilteringDelay = 200;
   st.Properties.ValueField = "Key";
   st.Properties.TextField = "Value";
}).BindList(Report.GetParameters()).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"mb\"");

WriteLiteral(">\r\n");

WriteLiteral("   ");

            
            #line 34 "..\..\Views\Report\EditTemplate.cshtml"
Write(Html.DevExpress().ComboBoxFor(m => m.Company, st =>
{
   st.Width = Unit.Percentage(100);
   st.Properties.Caption = "Áp dụng cho công ty";
   st.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
   st.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
   st.Properties.IncrementalFilteringDelay = 200;
   st.Properties.DropDownStyle = DropDownStyle.DropDown;
   st.Properties.AllowNull = true;
   st.Properties.ClearButton.DisplayMode = ClearButtonDisplayMode.Always;
   st.Properties.ValueField = "Oid";
   st.Properties.ValueType = typeof(int);
   st.Properties.TextField = "Name";
}).BindList(Report.GetCompanies()).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"mb\"");

WriteLiteral(">\r\n");

WriteLiteral("   ");

            
            #line 50 "..\..\Views\Report\EditTemplate.cshtml"
Write(Html.EditorFor(m => m.Active));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n");

WriteLiteral("   ");

            
            #line 53 "..\..\Views\Report\EditTemplate.cshtml"
Write(Html.EditorFor(m => m.Note));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
