#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/IndexPartial.cshtml")]
    public partial class _Views_Report_IndexPartial_cshtml : WebApp.Core.BaseWebViewPage<Report.ListInfo>
    {
        public _Views_Report_IndexPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Report\IndexPartial.cshtml"
Write(Html.DevExpress().GridView(st =>
{
   var toolDesigner = new MVCxGridViewToolbarItem();
   toolDesigner.Name = "designer";
   toolDesigner.Text = T("Thiết kế");
   toolDesigner.Image.IconID = IconID.ReportsDesignreport16x16;
   toolDesigner.Command = GridViewToolbarCommand.Custom;
   toolDesigner.Visible = CheckPermission("Thiết kế mẫu");
   Html.DefaultGridSheet(st, Model.ShowFilter, true, new MVCxGridViewToolbarItem[] { toolDesigner });

   st.Columns.Add(col =>
   {
      col.FieldName = "Category";
      col.Caption = T("Nhóm báo cáo");
      col.GroupIndex = 0;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Name";
      col.Caption = T("Tên báo cáo");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Company.Name";
      col.Caption = T("Áp dụng cho công ty");
      col.SettingsHeaderFilter.Mode = GridHeaderFilterMode.CheckedList;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Active";
      col.Caption = T("Sử dụng");
      col.Width = 80;
      col.ColumnType = MVCxGridViewColumnType.CheckBox;
   });
   st.PreviewFieldName = "Note";
   st.Settings.ShowPreview = true;
   st.SettingsBehavior.AutoExpandAllGroups = true;

}).BindToLINQ("", "", (s, e) =>
{
   e.QueryableSource = Model.GetData();
   e.DefaultSorting = "Name";
   e.KeyExpression = "Oid";
}).GetHtml());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
