#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Doctor/IndexPartial.cshtml")]
    public partial class _Views_Doctor_IndexPartial_cshtml : WebApp.Core.BaseWebViewPage<Doctor.ListInfo>
    {
        public _Views_Doctor_IndexPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Doctor\IndexPartial.cshtml"
Write(Html.DevExpress().GridView(st =>
{
   Html.DefaultGridSheet(st, Model.ShowFilter);
   if (WindowWidthType >= WebApp.Constant.WindowWidth.WidthType.Small && WindowWidthType <= WebApp.Constant.WindowWidth.WidthType.Medium)
   {
      st.Settings.HorizontalScrollBarMode = ScrollBarMode.Auto;
      st.Settings.ColumnMinWidth = 150;
   }

   st.Columns.Add(col =>
   {
      col.FieldName = "Code";
      col.Caption = T("Mã định danh");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Name";
      col.Caption = T("Họ và tên");
      col.Width = 150;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Gender.Name";
      col.Caption = T("Giới tính");
      col.Width = 80;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "DateBirth";
      col.Caption = T("Ngày sinh");
      col.ColumnType = MVCxGridViewColumnType.DateEdit;
      col.Width = WidthDate;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Phone";
      col.Caption = T("Điện thoại");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Email";
      col.Caption = T("Email");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Facility.Name";
      col.Caption = T("Đơn vị công tác");
      col.Width = 200;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Title.Name";
      col.Caption = T("Chức danh");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Qualification.Name";
      col.Caption = T("Trình độ");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Specialize.Name";
      col.Caption = T("Lĩnh vực chuyên môn");
      col.Width = 150;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Note";
      col.Caption = T("Ghi chú");
   });

}).BindToLINQ("", "", (s, e) =>
{
   e.QueryableSource = Model.GetData();
   e.DefaultSorting = "DateCreate desc";
   e.KeyExpression = "Oid";
}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
