#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Institution/EditTemplate.cshtml")]
    public partial class _Views_Institution_EditTemplate_cshtml : WebApp.Core.BaseWebViewPage<Institution>
    {
        public _Views_Institution_EditTemplate_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Institution\EditTemplate.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 5 "..\..\Views\Institution\EditTemplate.cshtml"
                  Write(Html.EditorFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n   <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 7 "..\..\Views\Institution\EditTemplate.cshtml"
                       Write(Html.EditorFor(m => m.Phone));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 8 "..\..\Views\Institution\EditTemplate.cshtml"
                       Write(Html.EditorFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-4_xs-12\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Institution\EditTemplate.cshtml"
                       Write(Html.EditorFor(m => m.Website));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 11 "..\..\Views\Institution\EditTemplate.cshtml"
                            Write(Html.EditorFor(m => m.Province));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\Institution\EditTemplate.cshtml"
                            Write(Html.EditorFor(m => m.District));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Institution\EditTemplate.cshtml"
                            Write(Html.EditorFor(m => m.Ward));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-3_md-12_xs-12\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Institution\EditTemplate.cshtml"
                             Write(Html.EditorFor(m => m.Address));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Institution\EditTemplate.cshtml"
                  Write(Html.EditorFor(m => m.Note));

            
            #line default
            #line hidden
WriteLiteral(@"</div>

</div>

<script>
   $(function () {
      Name.Focus();
      Province.ValueChanged.AddHandler(function () {
         District.SetValue(null);
         Ward.SetValue(null);
         District.PerformCallback();
         Ward.PerformCallback();
      });
      District.BeginCallback.AddHandler(function (_, e) {
         e.customArgs.province = Province.GetValue();
      });
      District.ValueChanged.AddHandler(function () {
         Ward.SetValue(null);
         Ward.PerformCallback();
      });
      Ward.BeginCallback.AddHandler(function (_, e) {
         e.customArgs.district = District.GetValue();
      });
   });
</script>");

        }
    }
}
#pragma warning restore 1591
