#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Institution/IndexPartial.cshtml")]
    public partial class _Views_Institution_IndexPartial_cshtml : WebApp.Core.BaseWebViewPage<Institution.ListInfo>
    {
        public _Views_Institution_IndexPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Institution\IndexPartial.cshtml"
Write(Html.DevExpress().GridView(st =>
{
   Html.DefaultGridSheet(st, Model.ShowFilter);
   if (WindowWidthType >= WebApp.Constant.WindowWidth.WidthType.Small && WindowWidthType <= WebApp.Constant.WindowWidth.WidthType.Medium)
   {
      st.Settings.HorizontalScrollBarMode = ScrollBarMode.Auto;
      st.Settings.ColumnMinWidth = 100;
   }

   st.Columns.Add(col =>
   {
      col.FieldName = "Name";
      col.Caption = T("Tên đơn vị");
      col.MinWidth = 300;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Province.Name";
      col.Caption = T("Tỉnh, thành phố");
      col.MinWidth = 150;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "District.Name";
      col.Caption = T("Quận, huyện");
      col.MinWidth = 120;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Ward.Name";
      col.Caption = T("Phường xã");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Phone";
      col.Caption = T("Điện thoại");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Email";
      col.Caption = T("Email");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Website";
      col.Caption = T("Website");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Note";
      col.Caption = T("Ghi chú");
   });

}).BindToLINQ("", "", (s, e) =>
{
   e.QueryableSource = Model.GetData();
   e.DefaultSorting = "Name";
   e.KeyExpression = "Oid";
}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
