//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebApp.DataModel
{

   public partial class AuditData : XPLiteObject
   {
      int fId;
      [Key(true)]
      public int Id
      {
         get { return fId; }
         set { SetPropertyValue<int>("Id", ref fId, value); }
      }
      string fAuditType;
      public string AuditType
      {
         get { return fAuditType; }
         set { SetPropertyValue<string>("AuditType", ref fAuditType, value); }
      }
      string fDescription;
      [Size(SizeAttribute.Unlimited)]
      public string Description
      {
         get { return fDescription; }
         set { SetPropertyValue<string>("Description", ref fDescription, value); }
      }
      int? fObjectId;
      public int? ObjectId
      {
         get { return fObjectId; }
         set { SetPropertyValue<int?>("ObjectId", ref fObjectId, value); }
      }
      string fObjectType;
      public string ObjectType
      {
         get { return fObjectType; }
         set { SetPropertyValue<string>("ObjectType", ref fObjectType, value); }
      }
      int? fCompany;
      public int? Company
      {
         get { return fCompany; }
         set { SetPropertyValue<int?>("Company", ref fCompany, value); }
      }
      int fUser;
      public int User
      {
         get { return fUser; }
         set { SetPropertyValue<int>("User", ref fUser, value); }
      }
      [Association(@"AuditChangeReferencesAuditData"), Aggregated]
      public XPCollection<AuditChange> Changes { get { return GetCollection<AuditChange>("Changes"); } }
   }

}
