//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebApp.DataModel
{

    public partial class AuditChange : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        AuditData fAudit;
        [Association(@"AuditChangeReferencesAuditData")]
        public AuditData Audit
        {
            get { return fAudit; }
            set { SetPropertyValue<AuditData>("Audit", ref fAudit, value); }
        }
        string fPropertyName;
        public string PropertyName
        {
            get { return fPropertyName; }
            set { SetPropertyValue<string>("PropertyName", ref fPropertyName, value); }
        }
        string fOldValue;
        [Size(SizeAttribute.Unlimited)]
        public string OldValue
        {
            get { return fOldValue; }
            set { SetPropertyValue<string>("OldValue", ref fOldValue, value); }
        }
        string fNewValue;
        [Size(SizeAttribute.Unlimited)]
        public string NewValue
        {
            get { return fNewValue; }
            set { SetPropertyValue<string>("NewValue", ref fNewValue, value); }
        }
    }

}
