//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebApp.DataModel
{

    public partial class Company : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fFullName;
        public string FullName
        {
            get { return fFullName; }
            set { SetPropertyValue<string>("FullName", ref fFullName, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>("Address", ref fAddress, value); }
        }
        string fPhone;
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>("Phone", ref fPhone, value); }
        }
        string fFax;
        public string Fax
        {
            get { return fFax; }
            set { SetPropertyValue<string>("Fax", ref fFax, value); }
        }
        string fWebsite;
        public string Website
        {
            get { return fWebsite; }
            set { SetPropertyValue<string>("Website", ref fWebsite, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        string fDirector;
        public string Director
        {
            get { return fDirector; }
            set { SetPropertyValue<string>("Director", ref fDirector, value); }
        }
        string fDirectorPhone;
        public string DirectorPhone
        {
            get { return fDirectorPhone; }
            set { SetPropertyValue<string>("DirectorPhone", ref fDirectorPhone, value); }
        }
        string fNote;
        [Size(SizeAttribute.Unlimited)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>("Note", ref fNote, value); }
        }
        bool fActive;
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>("Active", ref fActive, value); }
        }
        DateTime? fExpireDate;
        public DateTime? ExpireDate
        {
            get { return fExpireDate; }
            set { SetPropertyValue<DateTime?>("ExpireDate", ref fExpireDate, value); }
        }
        DateTime fRegisterDate;
        public DateTime RegisterDate
        {
            get { return fRegisterDate; }
            set { SetPropertyValue<DateTime>("RegisterDate", ref fRegisterDate, value); }
        }
        int fMaxUser;
        public int MaxUser
        {
            get { return fMaxUser; }
            set { SetPropertyValue<int>("MaxUser", ref fMaxUser, value); }
        }
        byte[] fLogo;
        [MemberDesignTimeVisibility(true)]
        public byte[] Logo
        {
            get { return fLogo; }
            set { SetPropertyValue<byte[]>("Logo", ref fLogo, value); }
        }
        [Association(@"UserCompanies", UseAssociationNameAsIntermediateTableName = true)]
        public XPCollection<User> Users { get { return GetCollection<User>("Users"); } }
    }

}
