//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebApp.DataModel
{

    public partial class PermisionDetail : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fModule;
        public string Module
        {
            get { return fModule; }
            set { SetPropertyValue<string>("Module", ref fModule, value); }
        }
        string fFunction;
        public string Function
        {
            get { return fFunction; }
            set { SetPropertyValue<string>("Function", ref fFunction, value); }
        }
        string fLogics;
        public string Logics
        {
            get { return fLogics; }
            set { SetPropertyValue<string>("Logics", ref fLogics, value); }
        }
        Permission fPermission;
        [Association(@"PermisionDetailReferencesPermission")]
        public Permission Permission
        {
            get { return fPermission; }
            set { SetPropertyValue<Permission>("Permission", ref fPermission, value); }
        }
    }

}
