//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebApp.DataModel
{

    public partial class Permission : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fNote;
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>("Note", ref fNote, value); }
        }
        int? fCompany;
        public int? Company
        {
            get { return fCompany; }
            set { SetPropertyValue<int?>("Company", ref fCompany, value); }
        }
        bool fSystem;
        public bool System
        {
            get { return fSystem; }
            set { SetPropertyValue<bool>("System", ref fSystem, value); }
        }
        [Association(@"ReportLayoutPermissions", UseAssociationNameAsIntermediateTableName = true)]
        public XPCollection<ReportLayout> Reports { get { return GetCollection<ReportLayout>("Reports"); } }
        [Association(@"PermisionDetailReferencesPermission"), Aggregated]
        public XPCollection<PermisionDetail> Details { get { return GetCollection<PermisionDetail>("Details"); } }
    }

}
