//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebApp.DataModel
{

    public partial class User : XPObject
    {
        string fUserName;
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>("UserName", ref fUserName, value); }
        }
        string fFullName;
        public string FullName
        {
            get { return fFullName; }
            set { SetPropertyValue<string>("FullName", ref fFullName, value); }
        }
        string fPasswordHash;
        public string PasswordHash
        {
            get { return fPasswordHash; }
            set { SetPropertyValue<string>("PasswordHash", ref fPasswordHash, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        string fSecurityStamp;
        public string SecurityStamp
        {
            get { return fSecurityStamp; }
            set { SetPropertyValue<string>("SecurityStamp", ref fSecurityStamp, value); }
        }
        bool fEmailConfirmed;
        public bool EmailConfirmed
        {
            get { return fEmailConfirmed; }
            set { SetPropertyValue<bool>("EmailConfirmed", ref fEmailConfirmed, value); }
        }
        bool fActive;
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>("Active", ref fActive, value); }
        }
        string fPhone;
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>("Phone", ref fPhone, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>("Address", ref fAddress, value); }
        }
        byte[] fImage;
        [MemberDesignTimeVisibility(true)]
        public byte[] Image
        {
            get { return fImage; }
            set { SetPropertyValue<byte[]>("Image", ref fImage, value); }
        }
        string fNote;
        [Size(SizeAttribute.Unlimited)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>("Note", ref fNote, value); }
        }
        Permission fPermission;
        public Permission Permission
        {
            get { return fPermission; }
            set { SetPropertyValue<Permission>("Permission", ref fPermission, value); }
        }
        int? fCurrentCompany;
        public int? CurrentCompany
        {
            get { return fCurrentCompany; }
            set { SetPropertyValue<int?>("CurrentCompany", ref fCurrentCompany, value); }
        }
        string fResetPasswordId;
        public string ResetPasswordId
        {
            get { return fResetPasswordId; }
            set { SetPropertyValue<string>("ResetPasswordId", ref fResetPasswordId, value); }
        }
        int? fGroupId;
        public int? GroupId
        {
            get { return fGroupId; }
            set { SetPropertyValue<int?>("GroupId", ref fGroupId, value); }
        }
        int? fDataId;
        public int? DataId
        {
            get { return fDataId; }
            set { SetPropertyValue<int?>("DataId", ref fDataId, value); }
        }
        [Association(@"UserCompanies", UseAssociationNameAsIntermediateTableName = true)]
        public XPCollection<Company> Companies { get { return GetCollection<Company>("Companies"); } }
        [Association(@"UserRoleReferencesUser"), Aggregated]
        public XPCollection<UserRole> Roles { get { return GetCollection<UserRole>("Roles"); } }
        [Association(@"UserLoginReferencesUser"), Aggregated]
        public XPCollection<UserLogin> Logins { get { return GetCollection<UserLogin>("Logins"); } }
    }

}
