//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebApp.DataModel
{

    public partial class UserLogin : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        User fUser;
        [Association(@"UserLoginReferencesUser")]
        public User User
        {
            get { return fUser; }
            set { SetPropertyValue<User>("User", ref fUser, value); }
        }
        string fLoginProvider;
        public string LoginProvider
        {
            get { return fLoginProvider; }
            set { SetPropertyValue<string>("LoginProvider", ref fLoginProvider, value); }
        }
        string fProviderKey;
        public string ProviderKey
        {
            get { return fProviderKey; }
            set { SetPropertyValue<string>("ProviderKey", ref fProviderKey, value); }
        }
    }

}
