//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace WebApp.DataModel
{

   public partial class UserClaim : XPLiteObject
   {
      int fId;
      [Key(true)]
      public int Id
      {
         get { return fId; }
         set { SetPropertyValue<int>("Id", ref fId, value); }
      }
      User fUser;
      [Association(@"UserClaimReferencesUser")]
      public User User
      {
         get { return fUser; }
         set { SetPropertyValue<User>("User", ref fUser, value); }
      }
      string fType;
      public string Type
      {
         get { return fType; }
         set { SetPropertyValue<string>("Type", ref fType, value); }
      }
      string fValue;
      public string Value
      {
         get { return fValue; }
         set { SetPropertyValue<string>("Value", ref fValue, value); }
      }
   }

}
