#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Patient/EditTemplate.cshtml")]
    public partial class _Views_Patient_EditTemplate_cshtml : WebApp.Core.BaseWebViewPage<Patient>
    {
        public _Views_Patient_EditTemplate_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Patient\EditTemplate.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 5 "..\..\Views\Patient\EditTemplate.cshtml"
                            Write(Html.EditorFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12 grid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-6\"");

WriteLiteral(">");

            
            #line 7 "..\..\Views\Patient\EditTemplate.cshtml"
                    Write(Html.EditorFor(m => m.Gender));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-6\"");

WriteLiteral(">");

            
            #line 8 "..\..\Views\Patient\EditTemplate.cshtml"
                    Write(Html.EditorFor(m => m.Folk));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"col-2_md-3_xs-12\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\Patient\EditTemplate.cshtml"
                            Write(Html.EditorFor(m => m.DateBirth));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n   <div");

WriteLiteral(" class=\"col-12 grid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-3_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Patient\EditTemplate.cshtml"
                               Write(Html.EditorFor(m => m.CMND));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-3_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Patient\EditTemplate.cshtml"
                               Write(Html.EditorFor(m => m.CCCD));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-3_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 15 "..\..\Views\Patient\EditTemplate.cshtml"
                               Write(Html.EditorFor(m => m.BHYT));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-3_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 16 "..\..\Views\Patient\EditTemplate.cshtml"
                               Write(Html.EditorFor(m => m.Phone));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   </div>\r\n\r\n");

WriteLiteral("   ");

            
            #line 19 "..\..\Views\Patient\EditTemplate.cshtml"
Write(Html.EditorFor(m => m, "Address"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Patient\EditTemplate.cshtml"
                            Write(Html.EditorFor(m => m.Classification));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12 levelDisability\"");

WriteLiteral(">");

            
            #line 22 "..\..\Views\Patient\EditTemplate.cshtml"
                                            Write(Html.EditorFor(m => m.LevelDisability));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-6_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Patient\EditTemplate.cshtml"
                            Write(Html.EditorFor(m => m.OrangeVictim));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Patient\EditTemplate.cshtml"
                  Write(Html.EditorFor(m => m.Disabilities));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Patient\EditTemplate.cshtml"
                  Write(Html.EditorFor(m => m.Note));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>\r\n\r\n<script>\r\n   $(function () {\r\n");

WriteLiteral("      ");

            
            #line 30 "..\..\Views\Patient\EditTemplate.cshtml"
  Write(Model.Id== 0 ? "Name.Focus();": "");

            
            #line default
            #line hidden
WriteLiteral(@"
      Classification.ValueChanged.AddHandler(function () {
         ToggleLevelDisability();
      });

      ToggleLevelDisability();
   });

   function CheckLevelDisability() {
      return Classification.GetValue() != 3;
   }

   function ToggleLevelDisability() {
      const v = Classification.GetValue();
      $('.levelDisability').toggle(v != 3);
   }
</script>");

        }
    }
}
#pragma warning restore 1591
