#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Patient/IndexPartial.cshtml")]
    public partial class _Views_Patient_IndexPartial_cshtml : WebApp.Core.BaseWebViewPage<Patient.ListInfo>
    {
        public _Views_Patient_IndexPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Patient\IndexPartial.cshtml"
Write(Html.DevExpress().GridView(st =>
{
   Html.DefaultGridSheet(st, Model.ShowFilter);
   if (WindowWidthType > WebApp.Constant.WindowWidth.WidthType.ExtraSmall)
      st.Settings.HorizontalScrollBarMode = ScrollBarMode.Auto;


   st.Columns.Add(col =>
   {
      col.FieldName = "Code";
      col.Caption = T("Mã định danh");
      col.MinWidth = 120;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Name";
      col.Caption = T("Họ và tên");
      col.MinWidth = 200;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "CMND";
      col.Caption = T("Số CMND");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "CCCD";
      col.Caption = T("Số CCCD");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "BHYT";
      col.Caption = T("Số thẻ BHYT");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Gender.Name";
      col.Caption = T("Giới tính");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Folk.Name";
      col.Caption = T("Dân tộc");
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "DateBirth";
      col.Caption = T("Ngày sinh");
      col.ColumnType = MVCxGridViewColumnType.DateEdit;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Phone";
      col.Caption = T("Điện thoại");
      col.MinWidth = 150;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Province.Name";
      col.Caption = T("Tỉnh, thành phố");
      col.MinWidth = 200;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "District.Name";
      col.Caption = T("Quận, huyện");
      col.MinWidth = 200;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Ward.Name";
      col.Caption = T("Phường, xã");
      col.MinWidth = 200;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Address";
      col.Caption = T("Địa chỉ");
      col.MinWidth = 200;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Classification.Name";
      col.Caption = T("Đối tượng khuyết tật");
      col.MinWidth = 300;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "LevelDisability.Name";
      col.Caption = T("Mức độ khuyết tật");
      col.MinWidth = 150;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "OrangeVictim.Name";
      col.Caption = T("Nạn nhân da cam");
      col.MinWidth = 300;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "DisabilitiesStr";
      col.Caption = T("Dạng khuyết tật");
      col.MinWidth = 300;
   });
   st.Columns.Add(col =>
   {
      col.FieldName = "Note";
      col.Caption = T("Ghi chú");
      col.MinWidth = 300;
   });

   st.FormatConditions.AddHighlight(c =>
   {
      c.ApplyToRow = false;
      c.FieldName = "Name";
      c.Format = GridConditionHighlightFormat.Custom;
      c.CellStyle.ForeColor = System.Drawing.Color.DarkOrange;
      c.Expression = "OrangeVictim.Oid == 1 || OrangeVictim.Oid == 2";
   });

}).BindToLINQ("", "", (s, e) =>
{
   e.QueryableSource = Model.GetData();
   e.DefaultSorting = "DateCreate desc";
   e.KeyExpression = "Oid";
}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
