#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebModule.MCNV.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Patient/ViewInfo.cshtml")]
    public partial class _Views_Patient_ViewInfo_cshtml : WebApp.Core.BaseWebViewPage<Patient.ViewInfo>
    {
        public _Views_Patient_ViewInfo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(">\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 4 "..\..\Views\Patient\ViewInfo.cshtml"
                            Write(Html.LockedText(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12 grid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-6\"");

WriteLiteral(">");

            
            #line 6 "..\..\Views\Patient\ViewInfo.cshtml"
                    Write(Html.LockedText(m => m.Gender));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-6\"");

WriteLiteral(">");

            
            #line 7 "..\..\Views\Patient\ViewInfo.cshtml"
                    Write(Html.LockedText(m => m.Folk));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"col-2_md-3_xs-12\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Patient\ViewInfo.cshtml"
                            Write(Html.LockedText(m => m.DateBirth));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n   <div");

WriteLiteral(" class=\"col-12 grid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"col-3_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 12 "..\..\Views\Patient\ViewInfo.cshtml"
                               Write(Html.LockedText(m => m.CMND));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-3_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 13 "..\..\Views\Patient\ViewInfo.cshtml"
                               Write(Html.LockedText(m => m.CCCD));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-3_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 14 "..\..\Views\Patient\ViewInfo.cshtml"
                               Write(Html.LockedText(m => m.BHYT));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n      <div");

WriteLiteral(" class=\"col-3_md-6_xs-12\"");

WriteLiteral(">");

            
            #line 15 "..\..\Views\Patient\ViewInfo.cshtml"
                               Write(Html.LockedText(m => m.Phone));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   </div>\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 17 "..\..\Views\Patient\ViewInfo.cshtml"
                  Write(Html.LockedText(m => m.Address));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-3_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\Patient\ViewInfo.cshtml"
                            Write(Html.LockedText(m => m.Classification));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 19 "..\..\Views\Patient\ViewInfo.cshtml"
   
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Patient\ViewInfo.cshtml"
    if (Model.ShowLevel)
   {

            
            #line default
            #line hidden
WriteLiteral("      <div");

WriteLiteral(" class=\"col-3_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 21 "..\..\Views\Patient\ViewInfo.cshtml"
                               Write(Html.LockedText(m => m.LevelDisability));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 22 "..\..\Views\Patient\ViewInfo.cshtml"
   }

            
            #line default
            #line hidden
WriteLiteral("   <div");

WriteLiteral(" class=\"col-6_md-4_xs-12\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Patient\ViewInfo.cshtml"
                            Write(Html.LockedText(m => m.OrangeVictim));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 24 "..\..\Views\Patient\ViewInfo.cshtml"
                  Write(Html.LockedText(m => m.Disabilities));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n   <div");

WriteLiteral(" class=\"col-12\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Patient\ViewInfo.cshtml"
                  Write(Html.LockedText(m => m.Note, true));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
