#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Decimal.cshtml")]
    public partial class _Views_Shared_EditorTemplates_Decimal_cshtml_ : WebApp.Core.BaseWebViewPage<object>
    {
        public _Views_Shared_EditorTemplates_Decimal_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\Decimal.cshtml"
  
   var caption = T(ViewData.ModelMetadata.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 6 "..\..\Views\Shared\EditorTemplates\Decimal.cshtml"
Write(Html.DevExpress().TextBoxFor(m => m, st =>
{
   st.Width = Unit.Percentage(100);
   st.Properties.Caption = caption;
   st.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
   st.Properties.DisplayFormatString = "N0";
   st.Properties.MaskSettings.Mask = "<0..999999999999g>";
   st.Properties.MaskSettings.IncludeLiterals = MaskIncludeLiteralsMode.None;
   st.ShowModelErrors = true;
   st.Properties.ValidationSettings.Display = Display.Dynamic;
   st.Properties.MaskSettings.AllowMouseWheel = false;
   st.Properties.EnableClientSideAPI = true;
}).Bind(Math.Round(Convert.ToDecimal(Model), 0)).GetHtml());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
