#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/PeriodParameter.cshtml")]
    public partial class _Views_Shared_EditorTemplates_PeriodParameter_cshtml_ : WebApp.Core.BaseWebViewPage<PeriodParameter>
    {

#line 2 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
public System.Web.WebPages.HelperResult Options()
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 3 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "   <div");

WriteLiteralTo(__razor_helper_writer, " class=\"grid-noGutter mb pt\"");

WriteLiteralTo(__razor_helper_writer, " style=\"border-top: solid 1px #a3a3a3;\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n      <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-6_xs-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n         <div");

WriteLiteralTo(__razor_helper_writer, " tg-option=\"1\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 6 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
WriteTo(__razor_helper_writer, T("Tuần hiện tại"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>\r\n         <div");

WriteLiteralTo(__razor_helper_writer, " tg-option=\"2\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 7 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
WriteTo(__razor_helper_writer, T("Tuần trước"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>\r\n      </div>\r\n      <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-6_xs-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n         <div");

WriteLiteralTo(__razor_helper_writer, " tg-option=\"3\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 10 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
WriteTo(__razor_helper_writer, T("Tháng hiện tại"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>\r\n         <div");

WriteLiteralTo(__razor_helper_writer, " tg-option=\"4\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 11 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
WriteTo(__razor_helper_writer, T("Tháng trước"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>\r\n      </div>\r\n   </div>\r\n");

WriteLiteralTo(__razor_helper_writer, "   <div");

WriteLiteralTo(__razor_helper_writer, " class=\"grid-noGutter mb\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n      <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-6_xs-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n         <div");

WriteLiteralTo(__razor_helper_writer, " tg-option=\"5\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 16 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
WriteTo(__razor_helper_writer, T("Quý hiện tại"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>\r\n         <div");

WriteLiteralTo(__razor_helper_writer, " tg-option=\"6\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 17 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
WriteTo(__razor_helper_writer, T("Quý trước"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>\r\n      </div>\r\n      <div");

WriteLiteralTo(__razor_helper_writer, " class=\"col-6_xs-12\"");

WriteLiteralTo(__razor_helper_writer, ">\r\n         <div");

WriteLiteralTo(__razor_helper_writer, " tg-option=\"7\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 20 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
WriteTo(__razor_helper_writer, T("Năm nay"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>\r\n         <div");

WriteLiteralTo(__razor_helper_writer, " tg-option=\"8\"");

WriteLiteralTo(__razor_helper_writer, ">");


#line 21 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
WriteTo(__razor_helper_writer, T("Năm qua"));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "</div>\r\n      </div>\r\n   </div>\r\n");


#line 24 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"


#line default
#line hidden
});

#line 24 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
}
#line default
#line hidden

        public _Views_Shared_EditorTemplates_PeriodParameter_cshtml_()
        {
        }
        public override void Execute()
        {
WriteLiteral("<style>\r\n   div[tg-option] {\r\n      padding: 2px 10px;\r\n      margin: 0 5px;\r\n   " +
"   cursor: pointer;\r\n   }\r\n\r\n      div[tg-option]:hover {\r\n         background-c" +
"olor: #c0c0c0;\r\n      }\r\n</style>\r\n");

            
            #line 36 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
Write(Html.DevExpress().DropDownEditFor(m => m.ThoiGian, st =>
{
   st.Width = Unit.Percentage(100);
   st.ShowModelErrors = true;
   st.Properties.ValidationSettings.Display = Display.Dynamic;
   st.ReadOnly = true;
   st.SetDropDownWindowTemplateContent(c =>
   {
      ViewContext.Writer.WriteLine("<div class='mt ml mr'>");
      Html.DevExpress().DateEditFor(m => m.TuNgay, s =>
      {
         s.Width = Unit.Percentage(100);
         s.ShowModelErrors = true;
         s.Properties.ValidationSettings.Display = Display.Dynamic;
         s.Properties.MaxDate = DateTime.Today;
         s.Properties.Caption = T("Từ ngày");
         s.Properties.AllowNull = false;
         s.Properties.CaptionCellStyle.Width = 80;
         s.Properties.ClientSideEvents.ValueChanged = "function(s,e) {TuNgay_Changed();}";
      }).Render();
      ViewContext.Writer.WriteLine("</div><div class='mt ml mr mb'>");
      Html.DevExpress().DateEditFor(m => m.DenNgay, s =>
      {
         s.Width = Unit.Percentage(100);
         s.ShowModelErrors = true;
         s.Properties.ValidationSettings.Display = Display.Dynamic;
         s.Properties.MaxDate = DateTime.Today;
         s.Properties.Caption = T("Đến ngày");
         s.Properties.AllowNull = false;
         s.Properties.DateRangeSettings.StartDateEditID = "TuNgay";
         s.Properties.CaptionCellStyle.Width = 80;
         s.Properties.ClientSideEvents.ValueChanged = "function(s,e) {ThoiGian.SetValue(TinhThoiGian());}";
      }).Render();
      ViewContext.Writer.WriteLine("</div>");
      ViewContext.Writer.WriteLine(Options());
   });
   st.Properties.DropDownWindowStyle.Paddings.Padding = 10;
   st.Properties.ClientSideEvents.GotFocus = "function(s,e) {s.ShowDropDown();}";
}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" id=\"dxss_periodparameter\"");

WriteLiteral(">\r\n   function TinhThoiGian() {\r\n      var f = TuNgay.GetValue();\r\n      var t = " +
"DenNgay.GetValue();\r\n      if (f.getTime() == t.getTime())\r\n         return \'");

            
            #line 81 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
            Write(H("Ngày {0}"));

            
            #line default
            #line hidden
WriteLiteral("\'.format(TuNgay.GetText());\r\n      var l = new Date(t.getFullYear(), t.getMonth()" +
" + 1, 0);\r\n      if (f.getDate() == 1 && t.getDate() == l.getDate()) {\r\n        " +
" if (f.getMonth() == t.getMonth() && f.getFullYear() == t.getFullYear())\r\n      " +
"      return \'");

            
            #line 85 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
               Write(H("Tháng {0}"));

            
            #line default
            #line hidden
WriteLiteral("\'.format((f.getMonth() + 1) + \'/\' + f.getFullYear());\r\n         if (f.getMonth() " +
"% 3 == 0 && t.getMonth() == f.getMonth() + 2)\r\n            return \'");

            
            #line 87 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
               Write(H("Quý {0} năm {1}"));

            
            #line default
            #line hidden
WriteLiteral("\'.format(Math.floor(f.getMonth()/3) + 1, f.getFullYear());\r\n         if (f.getMon" +
"th() == 0 && t.getMonth() == 11 && f.getFullYear() == t.getFullYear())\r\n        " +
"    return \'");

            
            #line 89 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
               Write(H("Năm {0}"));

            
            #line default
            #line hidden
WriteLiteral("\'.format(t.getFullYear());\r\n         return \'");

            
            #line 90 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
            Write(H("Từ tháng {0} đến tháng {1}"));

            
            #line default
            #line hidden
WriteLiteral("\'.format((f.getMonth() + 1) + \'/\' + f.getFullYear(), (t.getMonth() + 1) + \'/\' + t" +
".getFullYear());\r\n      }\r\n      return \'");

            
            #line 92 "..\..\Views\Shared\EditorTemplates\PeriodParameter.cshtml"
         Write(H("Từ ngày {0} đến ngày {1}"));

            
            #line default
            #line hidden
WriteLiteral("\'.format(TuNgay.GetText(), DenNgay.GetText());\r\n   }\r\n\r\n   function TuNgay_Change" +
"d() {\r\n      var t = TuNgay.GetValue();\r\n      if (t.getDate() == 1) {\r\n        " +
" var l = new Date(t.getFullYear(), t.getMonth() + 1, 0);\r\n         DenNgay.SetVa" +
"lue(l);\r\n      }\r\n      ThoiGian.SetValue(TinhThoiGian());\r\n   }\r\n\r\n   $(\'div[tg" +
"-option]\').click(function () {\r\n      var v = parseInt($(this).attr(\'tg-option\')" +
") || 0;\r\n      if (!v) return;\r\n      var d = new Date();\r\n      d = new Date(d." +
"getFullYear(), d.getMonth(), d.getDate());\r\n      var day = d.getDay(),\r\n       " +
"  diff = d.getDate() - day + (day == 0 ? -6 : 1);\r\n      var w = new Date(d.getF" +
"ullYear(), d.getMonth(), diff);\r\n      var f, t;\r\n\r\n      switch (v) {\r\n        " +
" case 1:\r\n            f = new Date(w);\r\n            t = new Date(f.getFullYear()" +
", f.getMonth(), f.getDate() + 6);\r\n            break;\r\n         case 2:\r\n       " +
"     f = new Date(w.getFullYear(), w.getMonth(), w.getDate() - 7);\r\n            " +
"t = new Date(f.getFullYear(), f.getMonth(), f.getDate() + 6);\r\n            break" +
";\r\n         case 3:\r\n            f = new Date(d.getFullYear(), d.getMonth(), 1);" +
"\r\n            t = new Date(f.getFullYear(), f.getMonth() + 1, 0);\r\n            b" +
"reak;\r\n         case 4:\r\n            f = new Date(d.getFullYear(), d.getMonth() " +
"- 1, 1);\r\n            t = new Date(f.getFullYear(), f.getMonth() + 1, 0);\r\n     " +
"       break;\r\n         case 5:\r\n            f = new Date(d.getFullYear(), Math." +
"floor(d.getMonth() / 3) * 3, 1);\r\n            t = new Date(f.getFullYear(), f.ge" +
"tMonth() + 3, 0);\r\n            break;\r\n         case 6:\r\n            f = new Dat" +
"e(d.getFullYear(), Math.floor(d.getMonth() / 3) * 3 - 3, 1);\r\n            t = ne" +
"w Date(f.getFullYear(), f.getMonth() + 3, 0);\r\n            break;\r\n         case" +
" 7:\r\n            f = new Date(d.getFullYear(), 0, 1);\r\n            t = new Date(" +
"d.getFullYear(), 11, 31);\r\n            break;\r\n         case 8:\r\n            f =" +
" new Date(d.getFullYear() - 1, 0, 1);\r\n            t = new Date(d.getFullYear() " +
"- 1, 11, 31);\r\n            break;\r\n      }\r\n      TuNgay.SetValue(f);\r\n      Den" +
"Ngay.SetValue(t);\r\n      ThoiGian.SetValue(TinhThoiGian());\r\n      ThoiGian.Hide" +
"DropDown();\r\n   });\r\n   setTimeout(function () {\r\n      ThoiGian.SetValue(TinhTh" +
"oiGian());\r\n   });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
