#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using WebApp.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/String.cshtml")]
    public partial class _Views_Shared_EditorTemplates_String_cshtml_ : WebApp.Core.BaseWebViewPage<object>
    {
        public _Views_Shared_EditorTemplates_String_cshtml_()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\String.cshtml"
  
   Type tModel = ViewData.ModelMetadata.ModelType;
   var caption = T(ViewData.ModelMetadata.DisplayName);
   var length = 100;
   try
   {
      length = ViewData.ModelMetadata.ContainerType.GetMember(ViewData.ModelMetadata.PropertyName)[0]
          .GetCustomAttributes(typeof(WebApp.Core.LengthAttribute), true).Cast<WebApp.Core.LengthAttribute>().First().MaximumLength;
   }
   catch { }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\Shared\EditorTemplates\String.cshtml"
 if (typeof(string).IsAssignableFrom(tModel))
{

   
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Shared\EditorTemplates\String.cshtml"
Write(Html.DevExpress().TextBoxFor(m => m, txt =>
{
   txt.Width = Unit.Percentage(100);
   txt.Properties.Caption = caption;
   txt.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
   txt.ShowModelErrors = true;
   txt.Properties.ValidationSettings.Display = Display.Dynamic;
   txt.Properties.MaxLength = length;
   txt.Properties.EnableClientSideAPI = true;
   txt.AutoCompleteType = AutoCompleteType.Disabled;
   if (ViewData.ModelMetadata.IsRequired)
      txt.Properties.CaptionSettings.RequiredMarkDisplayMode = EditorRequiredMarkMode.Required;
}).GetHtml());

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\EditorTemplates\String.cshtml"
            
}
else if (typeof(Enum).IsAssignableFrom(tModel))
{
   
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\Shared\EditorTemplates\String.cshtml"
Write(Html.DevExpress().ComboBoxFor(m => m, s =>
{
   s.Width = Unit.Percentage(100);
   s.Properties.Caption = caption;
   s.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
   s.Properties.Items.AddRange(Enum.GetValues(tModel));
   s.SelectedIndex = 0;
   s.Properties.DropDownStyle = DropDownStyle.DropDownList;
   s.Properties.EnableClientSideAPI = true;
}).GetHtml());

            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Shared\EditorTemplates\String.cshtml"
            
}
            
            #line default
            #line hidden
WriteLiteral(" ");

        }
    }
}
#pragma warning restore 1591
